"""Claude Backtest Analyst -- post-backtest intelligence analysis.

Analyzes production_backtest.py output reports using Claude to identify:
  a) Which strategies work on which exchanges and why
  b) Specific threshold adjustment recommendations with numbers
  c) Concerning patterns (e.g., all profits from one ticker)
  d) Overall system score (1-10 scale)

Called manually after backtests complete, or automatically when
AEGIS_CLAUDE_ANALYSIS=1 env var is set and production_backtest.py finishes.

QUARANTINE: This module is READ-ONLY. It NEVER writes to WAL, config.toml,
dynamic_weights.toml, or any live trading parameter. Output goes only to
data/claude_backtest_analysis.json.

Usage:
    python3 -m python_brain.ouroboros.claude_backtest_analyst --report path/to/report.json
    python3 -m python_brain.ouroboros.claude_backtest_analyst --latest
    python3 -m python_brain.ouroboros.claude_backtest_analyst --report path/to/report.json --dry-run
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from python_brain.ouroboros.claude_intelligence import claude_analyze_json

log = logging.getLogger("claude_backtest_analyst")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_PROJECT_ROOT = Path(os.environ.get("AEGIS_ROOT", Path(__file__).resolve().parents[2]))
DATA_DIR = Path(os.environ.get("AEGIS_DATA_DIR", _PROJECT_ROOT / "data"))
REPORT_DIR = DATA_DIR / "backtest_reports"
OUTPUT_FILE = DATA_DIR / "claude_backtest_analysis.json"

# ---------------------------------------------------------------------------
# System prompt for backtest analysis
# ---------------------------------------------------------------------------
BACKTEST_SYSTEM_PROMPT = """\
You are the backtest analyst for AEGIS V2, an autonomous UK ISA leveraged ETP
trading engine. You have been given a production-parity backtest report that was
generated by feeding historical market data through the ACTUAL trading pipeline
(bridge.py + all gates + indicators + Chandelier exit).

Your task is to provide a rigorous, data-driven analysis of the backtest results.

ANALYSIS FRAMEWORK:
1. STRATEGY-EXCHANGE MATRIX: For each strategy, identify which exchanges it
   performs best/worst on and hypothesise why (regime fit, spread, liquidity).
2. THRESHOLD RECOMMENDATIONS: Suggest specific numeric adjustments to:
   - Confidence floor (currently per-leverage: 5x=80, 3x=65, unleveraged=45)
   - ADX threshold (currently 20 for entries)
   - RVOL threshold (currently 1.0 for entries)
   - Kelly fraction scaling
   - Chandelier rung thresholds
   Give exact numbers, not vague "increase/decrease".
3. PATTERN FLAGS: Identify concerning patterns such as:
   - All profits concentrated in 1-2 tickers (concentration risk)
   - Strategy that only works on one exchange
   - Win rate < 40% on any strategy (possible broken logic)
   - Profit factor < 1.2 on any strategy (not enough edge)
   - Avg rung < 1.0 (exits too early, not capturing trends)
4. SYSTEM SCORE: Rate overall system 1-10 based on:
   - Win Rate (target: >= 55%)
   - Profit Factor (target: >= 1.5)
   - Avg Rung (target: >= 2.0, shows trend capture)
   - Return % (target: positive after costs)
   - Diversification (not dependent on single ticker/strategy)

OUTPUT FORMAT (pure JSON, no markdown wrapping):
{
  "date": "YYYY-MM-DD",
  "status": "complete",
  "confidence": 0.0-1.0,
  "system_score": 1-10,
  "system_score_reasoning": "...",
  "strategy_exchange_matrix": [
    {
      "strategy": "strategy_name",
      "best_exchange": "exchange_name",
      "worst_exchange": "exchange_name",
      "win_rate": 0.0,
      "pnl": 0.0,
      "reasoning": "..."
    }
  ],
  "threshold_recommendations": [
    {
      "parameter": "param_name",
      "current_value": "...",
      "recommended_value": "...",
      "confidence": 0.0-1.0,
      "sample_size": 0,
      "reasoning": "..."
    }
  ],
  "pattern_flags": [
    {
      "severity": "HIGH|MEDIUM|LOW",
      "pattern": "description",
      "evidence": "specific numbers",
      "recommendation": "what to do"
    }
  ],
  "executive_summary": "2-3 sentence overall assessment",
  "top_performers": ["ticker1", "ticker2"],
  "worst_performers": ["ticker1", "ticker2"]
}

RULES:
1. Base all analysis on the data provided. Do not invent results.
2. Maximum 20% parameter change recommendation from current values.
3. Maximum 10% change for kelly_fraction.
4. All recommendations must include sample_size and confidence.
5. Classify confidence: HIGH (sample >= 50), MEDIUM (20-49), LOW (< 20).
6. If total trades < 30, set confidence to LOW and note insufficient data.
7. NEVER recommend removing a risk CHECK entirely.
"""


# ---------------------------------------------------------------------------
# Report loading
# ---------------------------------------------------------------------------
def _find_latest_report() -> Optional[Path]:
    """Find the most recent backtest report in REPORT_DIR."""
    if not REPORT_DIR.exists():
        return None
    reports = sorted(REPORT_DIR.glob("production_backtest_*.json"))
    return reports[-1] if reports else None


def _load_report(report_path: Path) -> Optional[Dict[str, Any]]:
    """Load a backtest report JSON file."""
    try:
        with open(report_path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        log.error("Failed to load report %s: %s", report_path, e)
        return None


# ---------------------------------------------------------------------------
# Context builder
# ---------------------------------------------------------------------------
def _build_context(report: Dict[str, Any]) -> str:
    """Build a structured context string from the backtest report."""
    parts = ["# AEGIS V2 Production-Parity Backtest Report\n"]

    # Overall metrics
    combined = report.get("combined", {})
    parts.append("## Overall Results")
    parts.append(f"  Period: {report.get('period_days', '?')} days, interval={report.get('interval', '?')}")
    parts.append(f"  Tickers tested: {report.get('tickers_tested', '?')}/{report.get('tickers_attempted', '?')}")
    parts.append(f"  Ticks sent: {report.get('ticks_sent', 0):,}")
    parts.append(f"  Signals generated: {report.get('signals_generated', 0):,}")
    parts.append(f"  Total trades: {combined.get('total_trades', 0)}")
    parts.append(f"  Wins: {combined.get('wins', 0)}, Losses: {combined.get('losses', 0)}")
    parts.append(f"  Win Rate: {combined.get('win_rate', 0):.1%}")
    parts.append(f"  Profit Factor: {combined.get('profit_factor', 0):.2f}")
    parts.append(f"  Total PnL: GBP {combined.get('total_pnl', 0):.2f}")
    parts.append(f"  Avg Rung: {combined.get('avg_rung', 0):.2f}")
    parts.append(f"  Avg Hold Bars: {combined.get('avg_hold_bars', 0):.1f}")
    parts.append(f"  Equity: GBP {combined.get('starting_equity', 0):,.2f} -> GBP {combined.get('ending_equity', 0):,.2f}")
    parts.append(f"  Return: {combined.get('return_pct', 0):+.1f}%")

    # Per-strategy breakdown
    per_strategy = report.get("per_strategy", {})
    if per_strategy:
        parts.append("\n## Per-Strategy Breakdown")
        for strat, s in sorted(per_strategy.items()):
            parts.append(
                f"  {strat}: trades={s.get('trades', 0)} "
                f"WR={s.get('win_rate', 0):.1%} "
                f"PnL=GBP {s.get('pnl', 0):+.2f} "
                f"avg_rung={s.get('avg_rung', 0):.2f}"
            )

    # Per-exchange breakdown (if available)
    per_exchange = report.get("per_exchange", {})
    if per_exchange:
        parts.append("\n## Per-Exchange Breakdown")
        for exch, e in sorted(per_exchange.items()):
            parts.append(
                f"  {exch}: trades={e.get('trades', 0)} "
                f"WR={e.get('win_rate', 0):.1%} "
                f"PnL=GBP {e.get('pnl', 0):+.2f}"
            )

    # Per-ticker breakdown (if available, limit to top/bottom 10)
    per_ticker = report.get("per_ticker", {})
    if per_ticker:
        sorted_tickers = sorted(per_ticker.items(), key=lambda x: x[1].get("pnl", 0), reverse=True)
        parts.append(f"\n## Top Performing Tickers (of {len(sorted_tickers)})")
        for t, td in sorted_tickers[:10]:
            parts.append(
                f"  {t}: trades={td.get('trades', 0)} "
                f"WR={td.get('win_rate', 0):.1%} "
                f"PnL=GBP {td.get('pnl', 0):+.2f}"
            )
        if len(sorted_tickers) > 10:
            parts.append(f"\n## Worst Performing Tickers")
            for t, td in sorted_tickers[-10:]:
                parts.append(
                    f"  {t}: trades={td.get('trades', 0)} "
                    f"WR={td.get('win_rate', 0):.1%} "
                    f"PnL=GBP {td.get('pnl', 0):+.2f}"
                )

    # Per-day breakdown (if available)
    per_day = report.get("per_day", {})
    if per_day:
        parts.append(f"\n## Daily P&L ({len(per_day)} days)")
        for day, dd in sorted(per_day.items()):
            parts.append(
                f"  {day}: trades={dd.get('trades', 0)} "
                f"PnL=GBP {dd.get('pnl', 0):+.2f} "
                f"WR={dd.get('win_rate', 0):.1%}"
            )

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Main analysis
# ---------------------------------------------------------------------------
def analyze_backtest_report(
    report_path: Optional[str] = None,
    dry_run: bool = False,
) -> Optional[Dict[str, Any]]:
    """Analyze a backtest report with Claude.

    Args:
        report_path: Path to the report JSON. If None, uses latest.
        dry_run: If True, show context without calling Claude.

    Returns:
        Analysis result dict, or None on failure.
    """
    # Load report
    if report_path:
        path = Path(report_path)
    else:
        path = _find_latest_report()
        if path is None:
            log.error("No backtest report found in %s", REPORT_DIR)
            return None

    log.info("Analyzing backtest report: %s", path)
    report = _load_report(path)
    if report is None:
        return None

    total_trades = report.get("combined", {}).get("total_trades", 0)
    if total_trades == 0:
        log.info("Report has 0 trades -- skipping analysis")
        result = {
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "status": "skipped",
            "confidence": 0.0,
            "reason": "no_trades_in_backtest",
            "report_path": str(path),
        }
        _save_output(result)
        return result

    # Build context
    context = _build_context(report)
    prompt = (
        f"Analyze this production-parity backtest report for AEGIS V2. "
        f"The backtest covered {report.get('period_days', '?')} days with "
        f"{report.get('interval', '?')} bars, producing {total_trades} trades. "
        f"Provide your full analysis per the framework in your system prompt. "
        f"Output pure JSON, no markdown code blocks."
    )

    if dry_run:
        print("=" * 60)
        print("  BACKTEST ANALYSIS DRY RUN")
        print("=" * 60)
        print(f"\nReport: {path}")
        print(f"Trades: {total_trades}")
        print(f"Context: {len(context)} chars")
        print(f"\n{context}")
        return {"date": datetime.now(timezone.utc).strftime("%Y-%m-%d"), "status": "dry_run"}

    # Call Claude
    full_context = BACKTEST_SYSTEM_PROMPT + "\n\n" + context
    result = claude_analyze_json(
        prompt=prompt,
        context=full_context,
        max_tokens=4096,
        timeout=120,
    )

    if result is None:
        log.error("Backtest analysis failed -- Claude returned no parseable response")
        result = {
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "status": "failed",
            "confidence": 0.0,
            "error": "claude_no_response",
        }
    else:
        result["status"] = result.get("status", "complete")
        result["generated_at"] = datetime.now(timezone.utc).isoformat()
        result["report_path"] = str(path)
        result["report_trades"] = total_trades

    _save_output(result)

    # Log summary
    score = result.get("system_score", "?")
    summary = result.get("executive_summary", "No summary")
    log.info("Backtest analysis complete: score=%s, summary=%s", score, summary[:100])
    return result


def _save_output(result: Dict[str, Any]) -> None:
    """Save analysis output to data/claude_backtest_analysis.json."""
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(OUTPUT_FILE, "w") as f:
            json.dump(result, f, indent=2, default=str)
        log.info("Backtest analysis saved: %s", OUTPUT_FILE)
    except OSError as e:
        log.error("Failed to save backtest analysis: %s", e)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [BacktestAnalyst] %(levelname)s %(message)s",
    )

    parser = argparse.ArgumentParser(
        description="Claude Backtest Analyst -- post-backtest intelligence"
    )
    parser.add_argument("--report", type=str, help="Path to backtest report JSON")
    parser.add_argument("--latest", action="store_true", help="Analyze the most recent report")
    parser.add_argument("--dry-run", action="store_true", help="Show context without calling Claude")
    parser.add_argument("--json", action="store_true", help="Output result as JSON to stdout")
    args = parser.parse_args()

    report_path = args.report
    if args.latest and not report_path:
        latest = _find_latest_report()
        if latest:
            report_path = str(latest)
        else:
            print("No backtest reports found")
            return

    result = analyze_backtest_report(report_path=report_path, dry_run=args.dry_run)

    if result and args.json and not args.dry_run:
        print(json.dumps(result, indent=2, default=str))
    elif result and not args.dry_run and not args.json:
        score = result.get("system_score", "?")
        summary = result.get("executive_summary", "No summary")
        print(f"\nBacktest Analysis: Score {score}/10")
        print(f"Summary: {summary}")
        flags = result.get("pattern_flags", [])
        if flags:
            print(f"\nPattern Flags ({len(flags)}):")
            for flag in flags:
                print(f"  [{flag.get('severity', '?')}] {flag.get('pattern', '?')}")


if __name__ == "__main__":
    main()
