"""Config Fixes & Infrastructure Utilities — Ouroboros analytics module.

P2-7:    FTT intraday exemption (transaction tax registry config)
v19-P2-1: Shadow book alert threshold (£5→£50)
v19-P2-3: Polygon→IBKR reverse symbology mapping
v19-P2-9: ASX DST detection (AEDT vs AEST)

Usage: python3 -m python_brain.ouroboros.config_fixes
"""

from __future__ import annotations

import json
import logging
import os
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from zoneinfo import ZoneInfo

_PROJECT_ROOT = Path(os.environ.get("AEGIS_ROOT", Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(_PROJECT_ROOT / "python_brain"))
sys.path.insert(0, str(_PROJECT_ROOT))

DATA_DIR = Path(os.environ.get("AEGIS_DATA_DIR", _PROJECT_ROOT / "data"))
CONFIG_DIR = Path(os.environ.get("AEGIS_CONFIG_DIR", _PROJECT_ROOT / "config"))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [ConfigFixes] %(levelname)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("config_fixes")


# ---------------------------------------------------------------------------
# P2-7: FTT (Financial Transaction Tax) Intraday Exemption
# ---------------------------------------------------------------------------
# French FTT: 0.30% on settled (T+2) purchases of French equities > €1B market cap
# Italian FTT: 0.10% on settled purchases of Italian equities
# Both EXEMPT intraday round-trips (entry + exit same calendar day).

# Store as integer basis points to avoid floating-point precision issues (v19-P2-7)
TRANSACTION_TAX_REGISTRY = {
    "FR": {
        "name": "France Financial Transaction Tax",
        "rate_bps": 30,          # 0.30% = 30 basis points
        "applies_to": "buy",     # Only on purchases
        "min_market_cap_eur": 1_000_000_000,  # €1B threshold
        "intraday_exempt": True,  # Same-day round-trips exempt
        "settlement": "T+2",
    },
    "IT": {
        "name": "Italy Financial Transaction Tax",
        "rate_bps": 10,          # 0.10% = 10 basis points
        "applies_to": "buy",
        "min_market_cap_eur": 500_000_000,
        "intraday_exempt": True,
        "settlement": "T+2",
    },
    "UK": {
        "name": "UK Stamp Duty Reserve Tax",
        "rate_bps": 50,          # 0.50% = 50 basis points
        "applies_to": "buy",
        "min_market_cap_eur": 0,  # All UK equities
        "intraday_exempt": False,  # UK SDRT applies regardless
        "settlement": "T+2",
        "note": "ETPs listed on LSE are generally EXEMPT from SDRT",
    },
    "IE": {
        "name": "Ireland Stamp Duty",
        "rate_bps": 100,         # 1.00%
        "applies_to": "buy",
        "min_market_cap_eur": 0,
        "intraday_exempt": False,
        "settlement": "T+2",
    },
}


def generate_ftt_toml() -> str:
    """Generate transaction_tax_registry.toml content.

    Uses integer basis points (not float percentages) per v19-P2-7.
    """
    lines = [
        "# Transaction Tax Registry — auto-generated by config_fixes.py",
        "# Rates stored as INTEGER BASIS POINTS to avoid float precision issues (v19-P2-7)",
        "# 30 bps = 0.30%, 10 bps = 0.10%, 50 bps = 0.50%",
        "",
    ]

    for country, tax in sorted(TRANSACTION_TAX_REGISTRY.items()):
        lines.append(f'[{country}]')
        lines.append(f'name = "{tax["name"]}"')
        lines.append(f'rate_bps = {tax["rate_bps"]}')
        lines.append(f'applies_to = "{tax["applies_to"]}"')
        lines.append(f'min_market_cap_eur = {tax["min_market_cap_eur"]}')
        lines.append(f'intraday_exempt = {"true" if tax["intraday_exempt"] else "false"}')
        lines.append(f'settlement = "{tax["settlement"]}"')
        if "note" in tax:
            lines.append(f'note = "{tax["note"]}"')
        lines.append("")

    return "\n".join(lines)


def write_ftt_config(config_dir: Path = CONFIG_DIR) -> Path:
    """Write transaction_tax_registry.toml atomically."""
    path = config_dir / "transaction_tax_registry.toml"
    content = generate_ftt_toml()

    tmp_path = path.with_suffix(".toml.tmp")
    tmp_path.write_text(content)
    os.rename(str(tmp_path), str(path))

    log.info(f"P2-7: Wrote FTT registry: {path} ({len(TRANSACTION_TAX_REGISTRY)} jurisdictions)")
    return path


def is_ftt_exempt(country: str, is_intraday: bool) -> bool:
    """Check if a trade is FTT-exempt.

    Args:
        country: ISO 2-letter country code
        is_intraday: True if entry and exit on same calendar day

    Returns:
        True if exempt from FTT
    """
    tax = TRANSACTION_TAX_REGISTRY.get(country)
    if tax is None:
        return True  # No FTT for this country
    if is_intraday and tax.get("intraday_exempt", False):
        return True
    return False


def ftt_cost_bps(country: str, is_intraday: bool) -> int:
    """Get FTT cost in basis points (0 if exempt)."""
    if is_ftt_exempt(country, is_intraday):
        return 0
    tax = TRANSACTION_TAX_REGISTRY.get(country, {})
    return tax.get("rate_bps", 0)


# ---------------------------------------------------------------------------
# v19-P2-1: Shadow Book Alert Threshold
# ---------------------------------------------------------------------------
# Current threshold £5 causes excessive Telegram alerts.
# Raise to max(£50, 0.5% of position value).

SHADOW_BOOK_THRESHOLD_GBP = 50.0
SHADOW_BOOK_THRESHOLD_PCT = 0.005  # 0.5%


def shadow_book_threshold(position_value_gbp: float) -> float:
    """Compute shadow book alert threshold.

    Returns max(£50, 0.5% of position value).
    Telegram alert fires only if shadow book divergence exceeds this.
    """
    return max(SHADOW_BOOK_THRESHOLD_GBP, position_value_gbp * SHADOW_BOOK_THRESHOLD_PCT)


# ---------------------------------------------------------------------------
# v19-P2-3: Polygon→IBKR Reverse Symbology Mapping
# ---------------------------------------------------------------------------
# Polygon uses tickers like "LSE:NVD3" or "XLON:QQQ3".
# IBKR uses "NVD3.L" (symbol + ".L" suffix for LSE).

POLYGON_TO_IBKR_EXCHANGE_MAP = {
    "LSE": ".L",
    "XLON": ".L",
    "XETRA": ".DE",
    "FRA": ".F",
    "EURONEXT": ".AS",  # Amsterdam default; Paris = .PA
    "EPA": ".PA",
    "TSE": ".T",
    "HKEX": ".HK",
    "SGX": ".SI",
    "KSE": ".KS",
    "ASX": ".AX",
}

# US exchanges don't need suffix
US_EXCHANGES = {"NYSE", "NASDAQ", "AMEX", "BATS", "ARCA", "IEX"}


def polygon_to_ibkr(polygon_ticker: str) -> str:
    """Convert Polygon ticker to IBKR format.

    Examples:
        "LSE:NVD3" → "NVD3.L"
        "XLON:QQQ3" → "QQQ3.L"
        "AAPL" → "AAPL"
        "TSE:7203" → "7203.T"
    """
    if ":" in polygon_ticker:
        exchange, symbol = polygon_ticker.split(":", 1)
        exchange = exchange.upper()

        if exchange in US_EXCHANGES:
            return symbol

        suffix = POLYGON_TO_IBKR_EXCHANGE_MAP.get(exchange, "")
        if suffix:
            return f"{symbol}{suffix}"

        log.warning(f"Unknown Polygon exchange: {exchange} for ticker {polygon_ticker}")
        return symbol

    return polygon_ticker  # Already in IBKR format or US ticker


def ibkr_to_polygon(ibkr_ticker: str) -> str:
    """Convert IBKR ticker to Polygon format.

    Examples:
        "NVD3.L" → "LSE:NVD3"
        "AAPL" → "AAPL"
        "7203.T" → "TSE:7203"
    """
    IBKR_TO_POLYGON = {v: k for k, v in POLYGON_TO_IBKR_EXCHANGE_MAP.items()}

    for suffix, exchange in sorted(IBKR_TO_POLYGON.items(), key=lambda x: -len(x[0])):
        if ibkr_ticker.endswith(suffix):
            symbol = ibkr_ticker[:-len(suffix)]
            return f"{exchange}:{symbol}"

    return ibkr_ticker  # US ticker


# ---------------------------------------------------------------------------
# v19-P2-9: ASX DST Detection (AEDT vs AEST)
# ---------------------------------------------------------------------------
# ASX session open differs by 1 hour depending on Australian DST:
#   AEDT (UTC+11): ASX opens at 23:00 UTC (previous day)
#   AEST (UTC+10): ASX opens at 00:00 UTC

def get_asx_open_utc(when: Optional[datetime] = None) -> Tuple[int, int]:
    """Get ASX opening time in UTC, accounting for Australian DST.

    Returns:
        (hour, minute) in UTC when ASX opens
    """
    if when is None:
        when = datetime.now(timezone.utc)

    sydney_tz = ZoneInfo("Australia/Sydney")
    sydney_now = when.astimezone(sydney_tz)
    utc_offset = sydney_now.utcoffset()

    if utc_offset is None:
        # Fallback: assume AEST (UTC+10)
        return (0, 0)

    offset_hours = utc_offset.total_seconds() / 3600

    # ASX opens at 10:00 local Sydney time
    asx_local_open_hour = 10
    asx_open_utc_hour = int(asx_local_open_hour - offset_hours) % 24

    if offset_hours == 11:  # AEDT
        log.info("v19-P2-9: ASX DST=AEDT (UTC+11), open=23:00 UTC (prev day)")
    else:  # AEST
        log.info(f"v19-P2-9: ASX DST=AEST (UTC+{offset_hours:.0f}), open={asx_open_utc_hour:02d}:00 UTC")

    return (asx_open_utc_hour, 0)


def is_australian_dst(when: Optional[datetime] = None) -> bool:
    """Check if Australia is currently in daylight saving time."""
    if when is None:
        when = datetime.now(timezone.utc)

    sydney_tz = ZoneInfo("Australia/Sydney")
    sydney_now = when.astimezone(sydney_tz)
    offset = sydney_now.utcoffset()

    if offset is None:
        return False

    return offset.total_seconds() / 3600 == 11


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
def main():
    import argparse
    parser = argparse.ArgumentParser(description="Config fixes and infrastructure utilities")
    parser.add_argument("--write-ftt", action="store_true", help="Write FTT registry TOML")
    parser.add_argument("--test-polygon", type=str, help="Convert Polygon ticker to IBKR")
    parser.add_argument("--test-ibkr", type=str, help="Convert IBKR ticker to Polygon")
    parser.add_argument("--asx-open", action="store_true", help="Show current ASX open time")
    parser.add_argument("--shadow-threshold", type=float, help="Compute shadow book threshold for position value")
    parser.add_argument("--all", action="store_true", help="Run all checks")
    args = parser.parse_args()

    if args.write_ftt or args.all:
        path = write_ftt_config()
        print(f"FTT registry written to {path}")
        for country, tax in sorted(TRANSACTION_TAX_REGISTRY.items()):
            exempt = "YES" if tax["intraday_exempt"] else "NO"
            print(f"  {country}: {tax['rate_bps']}bps, intraday_exempt={exempt}")

    if args.test_polygon:
        result = polygon_to_ibkr(args.test_polygon)
        print(f"Polygon '{args.test_polygon}' → IBKR '{result}'")

    if args.test_ibkr:
        result = ibkr_to_polygon(args.test_ibkr)
        print(f"IBKR '{args.test_ibkr}' → Polygon '{result}'")

    if args.asx_open or args.all:
        hour, minute = get_asx_open_utc()
        dst = is_australian_dst()
        print(f"\nASX Open: {hour:02d}:{minute:02d} UTC (DST={'AEDT' if dst else 'AEST'})")

    if args.shadow_threshold is not None:
        threshold = shadow_book_threshold(args.shadow_threshold)
        print(f"Shadow book threshold for £{args.shadow_threshold:.0f} position: £{threshold:.2f}")

    if args.all:
        # Test some Polygon conversions
        test_tickers = ["LSE:NVD3", "XLON:QQQ3", "AAPL", "TSE:7203", "EPA:TTE"]
        print("\nPolygon→IBKR mapping test:")
        for t in test_tickers:
            print(f"  {t} → {polygon_to_ibkr(t)}")

        print(f"\nShadow book: threshold(£1000) = £{shadow_book_threshold(1000):.2f}")
        print(f"Shadow book: threshold(£100) = £{shadow_book_threshold(100):.2f}")

        print(f"\nFTT cost: FR intraday = {ftt_cost_bps('FR', True)}bps (exempt)")
        print(f"FTT cost: FR overnight = {ftt_cost_bps('FR', False)}bps")
        print(f"FTT cost: UK intraday = {ftt_cost_bps('UK', True)}bps (NOT exempt)")


if __name__ == "__main__":
    main()
