//! Core #[pyclass] structs for AEGIS V2 data contracts.
//! MarketTick, OrderIntent, RiskDecision + validate_f64 helper.
//! Fields ordered largest-to-smallest for struct packing (H128).

use pyo3::prelude::*;
use std::collections::HashMap;

use super::enums::*;

// ============================================================================
// CORE STRUCTS
// ============================================================================

/// A single market data tick from IBKR.
/// Rust owns these. Python receives Vec<MarketTick> via PyO3.
/// Fields ordered largest-to-smallest for struct packing (H128).
#[derive(Clone, Debug)]
#[pyclass]
pub struct MarketTick {
    /// Unix epoch nanoseconds from IBKR server (H03). NOT wall clock.
    #[pyo3(get)]
    pub timestamp_ns: u64,
    /// Socket-level receive timestamp for T2T latency (H118)
    #[pyo3(get)]
    pub recv_timestamp_ns: u64,
    /// Cumulative volume (resets daily)
    #[pyo3(get)]
    pub volume: u64,
    /// Best bid price
    #[pyo3(get)]
    pub bid: f64,
    /// Best ask price
    #[pyo3(get)]
    pub ask: f64,
    /// Last traded price
    #[pyo3(get)]
    pub last: f64,
    /// Best bid size (lots) — from L1 field 0 or L2 depth. 0 if unavailable.
    #[pyo3(get)]
    pub bid_size: i32,
    /// Best ask size (lots) — from L1 field 3 or L2 depth. 0 if unavailable.
    #[pyo3(get)]
    pub ask_size: i32,
    /// Interned ticker ID (H01). NOT a String.
    #[pyo3(get)]
    pub ticker_id: TickerId,
}

#[pymethods]
impl MarketTick {
    #[new]
    #[pyo3(signature = (ticker_id, bid, ask, last, volume, timestamp_ns, recv_timestamp_ns, bid_size=0, ask_size=0))]
    fn new(
        ticker_id: TickerId,
        bid: f64,
        ask: f64,
        last: f64,
        volume: u64,
        timestamp_ns: u64,
        recv_timestamp_ns: u64,
        bid_size: i32,
        ask_size: i32,
    ) -> Self {
        Self {
            timestamp_ns,
            recv_timestamp_ns,
            volume,
            bid,
            ask,
            last,
            bid_size,
            ask_size,
            ticker_id,
        }
    }

    fn __repr__(&self) -> String {
        format!(
            "MarketTick(ticker={}, bid={}, ask={}, last={}, vol={})",
            self.ticker_id.0, self.bid, self.ask, self.last, self.volume
        )
    }
}

impl MarketTick {
    /// Validate tick data is sane (not NaN/Inf, non-negative, bid < ask).
    #[inline(always)]
    pub fn is_valid(&self) -> bool {
        let f = |v: f64| v.is_finite() && v >= 0.0;
        f(self.bid) && f(self.ask) && f(self.last) && f(self.volume as f64)
            && (self.bid == 0.0 || self.ask == 0.0 || self.ask >= self.bid)
            && self.last >= 0.0
    }
}

/// Validate that an f64 is not NaN or Infinite (H09).
/// Returns Err with a descriptive message if invalid.
pub fn validate_f64(value: f64, field_name: &str) -> Result<f64, String> {
    if value.is_nan() {
        return Err(format!("NaN detected in field '{field_name}'"));
    }
    if value.is_infinite() {
        return Err(format!("Infinity detected in field '{field_name}'"));
    }
    Ok(value)
}

/// Generated by Python Brain. Crosses PyO3 back to Rust.
/// Python SUGGESTS. Rust DECIDES. Python has no gun (Non-Negotiable #2).
#[derive(Clone, Debug)]
#[pyclass]
pub struct OrderIntent {
    /// Signal confidence [0.0, 100.0]. Floor is 65.
    #[pyo3(get)]
    pub confidence: f64,
    /// Kelly fraction output from 12-factor sizing [0.0, 0.20]
    #[pyo3(get)]
    pub kelly_fraction: f64,
    /// Interned ticker ID
    #[pyo3(get)]
    pub ticker_id: TickerId,
    /// Long only in ISA (Short exists for type completeness but always rejected)
    #[pyo3(get)]
    pub side: Direction,
    /// Which strategy generated this intent
    #[pyo3(get)]
    pub strategy: StrategyId,
    /// Strategy-specific features for logging/Ouroboros analysis
    pub features: HashMap<String, f64>,
}

#[pymethods]
impl OrderIntent {
    #[new]
    #[pyo3(signature = (ticker_id, side, confidence, strategy, kelly_fraction, features=None))]
    fn new(
        ticker_id: TickerId,
        side: Direction,
        confidence: f64,
        strategy: StrategyId,
        kelly_fraction: f64,
        features: Option<HashMap<String, f64>>,
    ) -> PyResult<Self> {
        // NaN sanitization on every f64 from Python (H09)
        let confidence = validate_f64(confidence, "confidence")
            .map_err(pyo3::exceptions::PyValueError::new_err)?;
        let kelly_fraction = validate_f64(kelly_fraction, "kelly_fraction")
            .map_err(pyo3::exceptions::PyValueError::new_err)?;

        // Clamp confidence to [0.0, 100.0]
        let confidence = confidence.clamp(0.0, 100.0);
        // Clamp kelly_fraction to [0.0, 0.20] (H57)
        let kelly_fraction = kelly_fraction.clamp(0.0, 0.20);

        Ok(Self {
            confidence,
            kelly_fraction,
            ticker_id,
            side,
            strategy,
            features: features.unwrap_or_default(),
        })
    }

    fn __repr__(&self) -> String {
        format!(
            "OrderIntent(ticker={}, side={:?}, conf={:.1}, kelly={:.4})",
            self.ticker_id.0, self.side, self.confidence, self.kelly_fraction
        )
    }

    /// Get features as a Python dict
    #[getter]
    fn features(&self) -> HashMap<String, f64> {
        self.features.clone()
    }
}

/// The RiskArbiter's verdict on an OrderIntent.
#[derive(Clone, Debug)]
#[pyclass]
pub struct RiskDecision {
    /// Timestamp of decision (IBKR-adjusted clock)
    #[pyo3(get)]
    pub decision_timestamp_ns: u64,
    /// Adjusted position size (may be reduced in REDUCE regime)
    #[pyo3(get)]
    pub adjusted_size: f64,
    /// true = proceed to WAL + broker; false = rejected
    #[pyo3(get)]
    pub approved: bool,
    /// Current Risk Arbiter regime at decision time
    #[pyo3(get)]
    pub regime: RiskRegime,
    /// Specific reason for veto (or VetoReason::Approved)
    pub reason: VetoReason,
}

#[pymethods]
impl RiskDecision {
    #[new]
    #[pyo3(signature = (approved, adjusted_size, regime, decision_timestamp_ns))]
    fn new(
        approved: bool,
        adjusted_size: f64,
        regime: RiskRegime,
        decision_timestamp_ns: u64,
    ) -> Self {
        let reason = if approved {
            VetoReason::Approved
        } else {
            VetoReason::MaxPositionsReached // Default; real code sets specific reason
        };
        Self {
            decision_timestamp_ns,
            adjusted_size,
            approved,
            regime,
            reason,
        }
    }

    /// Get the veto reason as a Python-visible object
    #[getter]
    fn reason(&self) -> PyVetoReason {
        PyVetoReason::from(&self.reason)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_market_tick_field_packing() {
        let tick = MarketTick {
            timestamp_ns: 1_000_000_000,
            recv_timestamp_ns: 1_000_000_100,
            volume: 50000,
            bid: 10.50,
            ask: 10.52,
            last: 10.51,
            bid_size: 0,
            ask_size: 0,
            ticker_id: TickerId(42),
        };
        assert_eq!(tick.ticker_id, TickerId(42));
        assert_eq!(tick.bid, 10.50);
    }

    #[test]
    fn test_validate_f64_nan() {
        assert!(validate_f64(f64::NAN, "test").is_err());
    }

    #[test]
    fn test_validate_f64_infinity() {
        assert!(validate_f64(f64::INFINITY, "test").is_err());
        assert!(validate_f64(f64::NEG_INFINITY, "test").is_err());
    }

    #[test]
    fn test_validate_f64_valid() {
        assert!(validate_f64(42.0, "test").is_ok());
        assert!(validate_f64(0.0, "test").is_ok());
        assert!(validate_f64(-1.5, "test").is_ok());
    }
}
