//! Entry signal generation with 4 entry types, tier routing, and confidence decay.
//! Type A (40 LOC) + Type B (50 LOC) + Type C (40 LOC) + Type D (30 LOC)
//! Tier routing + Confidence decay (20 LOC)

// ╔════════════════════════════════════════════════════════════════════════════╗
// ║                          QUARANTINE NOTICE                               ║
// ║                                                                          ║
// ║  The TypeA-F detector structs in this file are DEAD CODE at runtime.     ║
// ║  All entry classification is performed by Python bridge.py, which sends  ║
// ║  pre-classified signals (TypeA-F) to the Rust engine. The Rust engine    ║
// ║  never instantiates DipRecoveryDetector, EarlyRunnerDetector,            ║
// ║  OverboughtFadeDetector, SupportBounceDetector, IBSMeanReversionDetector,║
// ║  or OBVDivergenceDetector.                                               ║
// ║                                                                          ║
// ║  WHAT IS STILL USED:                                                     ║
// ║    - EntryType enum          (referenced by types flowing from Python)    ║
// ║    - EntrySignal struct      (data contract)                             ║
// ║    - EntryTypeConfig         (config deserialization)                     ║
// ║    - Tier enum               (imported by position_sizer.rs)             ║
// ║    - apply_confidence_decay  (utility)                                   ║
// ║    - select_entry_types_by_tier (utility)                                ║
// ║                                                                          ║
// ║  DO NOT DELETE — the module is imported by lib.rs and position_sizer.rs. ║
// ║  The file must remain compilable. The detectors are kept for potential    ║
// ║  future Rust-native signal generation (S3+).                             ║
// ║                                                                          ║
// ║  Quarantined: 2026-03-24                                                 ║
// ╚════════════════════════════════════════════════════════════════════════════╝

use crate::types::{Direction, StrategyId, TickerId};
use std::collections::VecDeque;

// ============================================================================
// Entry Signal Types & Base Structure (40 LOC)
// ============================================================================

/// Entry signal classification
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntryType {
    /// Type A: Support bounce from recent lows (65% base confidence)
    DipRecovery,
    /// Type B: Momentum before overbought forms — YOUR EDGE (82% base confidence)
    EarlyRunner,
    /// Type C: Shorting via inverse ETPs (72% base confidence)
    OverboughtFade,
    /// Type D: Daily low bounce (70% base confidence)
    SupportBounce,
    /// Type E: IBS mean reversion (IBS < 0.1 + RVOL > 1.0 + mean_reverting)
    IBSMeanReversion,
    /// Type F: OBV divergence (OBV-RSI < 30 + RVOL > 0.7)
    OBVDivergence,
}

/// Entry signal generated by any entry detector
#[derive(Debug, Clone)]
pub struct EntrySignal {
    /// Which entry type triggered
    pub entry_type: EntryType,
    /// Base confidence before decay [0.0, 100.0]
    pub base_confidence: f64,
    /// Interned ticker ID for this entry
    pub ticker_id: TickerId,
    /// Direction (Long only in ISA)
    pub side: Direction,
    /// Strategy that generated this
    pub strategy: StrategyId,
}

impl EntrySignal {
    /// Create a new entry signal with all required fields
    pub fn new(
        entry_type: EntryType,
        base_confidence: f64,
        ticker_id: TickerId,
        side: Direction,
        strategy: StrategyId,
    ) -> Self {
        Self {
            entry_type,
            base_confidence: base_confidence.clamp(0.0, 100.0),
            ticker_id,
            side,
            strategy,
        }
    }
}

// ============================================================================
// Entry Type A: Dip Recovery (40 LOC)
// ============================================================================

/// Sprint 6: Configurable entry type parameters (from config.toml [entry_types]).
#[derive(Clone, Debug)]
pub struct EntryTypeConfig {
    pub type_a_confidence: f64,
    pub type_b_confidence: f64,
    pub type_c_confidence: f64,
    pub type_d_confidence: f64,
    pub type_a_rsi_oversold: f64,
    pub type_a_volume_spike_mult: f64,
    pub type_a_drop_atr_mult: f64,
    pub type_b_rsi_low: f64,
    pub type_b_rsi_high: f64,
    pub type_b_momentum_bars: usize,
    pub type_c_rsi_overbought: f64,
    pub type_d_price_proximity_pct: f64,
    pub type_d_rsi_low: f64,
    pub type_d_rsi_high: f64,
    pub confidence_decay_rate_per_hour: f64,
    pub type_e_confidence: f64,
    pub type_e_ibs_threshold: f64,
    pub type_e_rvol_threshold: f64,
    pub type_f_confidence: f64,
    pub type_f_obv_rsi_threshold: f64,
    pub type_f_rvol_threshold: f64,
}

impl Default for EntryTypeConfig {
    fn default() -> Self {
        Self {
            type_a_confidence: 65.0,
            type_b_confidence: 82.0,
            type_c_confidence: 72.0,
            type_d_confidence: 80.0,
            type_a_rsi_oversold: 40.0,
            type_a_volume_spike_mult: 1.8,
            type_a_drop_atr_mult: 2.0,
            type_b_rsi_low: 30.0,
            type_b_rsi_high: 70.0,
            type_b_momentum_bars: 3,
            type_c_rsi_overbought: 75.0,
            type_d_price_proximity_pct: 1.0,
            type_d_rsi_low: 20.0,
            type_d_rsi_high: 40.0,
            confidence_decay_rate_per_hour: 2.1,
            type_e_confidence: 70.0,
            type_e_ibs_threshold: 0.10,
            type_e_rvol_threshold: 1.0,
            type_f_confidence: 68.0,
            type_f_obv_rsi_threshold: 30.0,
            type_f_rvol_threshold: 0.7,
        }
    }
}

/// Type A: Price drops 2+ ATR from recent high, RSI oversold, volume expanding.
/// Entry logic: Buy the dip when volatility spike + weak hands panic.
pub struct DipRecoveryDetector;

impl DipRecoveryDetector {
    /// Detect Type A entry with configurable thresholds.
    pub fn detect_cfg(
        rsi: f64,
        rvol: f64,
        vol_ma20: f64,
        price_drop_atr_multiple: f64,
        ticker_id: TickerId,
        cfg: &EntryTypeConfig,
    ) -> Option<EntrySignal> {
        let trigger = rsi < cfg.type_a_rsi_oversold
            && rvol > vol_ma20 * cfg.type_a_volume_spike_mult
            && price_drop_atr_multiple >= cfg.type_a_drop_atr_mult;

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::DipRecovery,
                base_confidence: cfg.type_a_confidence,
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }

    /// Legacy detect with hardcoded defaults (backward compat for tests).
    pub fn detect(
        rsi: f64,
        rvol: f64,
        vol_ma20: f64,
        price_drop_atr_multiple: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        Self::detect_cfg(rsi, rvol, vol_ma20, price_drop_atr_multiple, ticker_id, &EntryTypeConfig::default())
    }
}

#[cfg(test)]
mod type_a_tests {
    use super::*;

    #[test]
    fn test_type_a_triggered_all_conditions_met() {
        let signal = DipRecoveryDetector::detect(35.0, 2.0, 1.0, 2.5, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::DipRecovery);
        assert_eq!(sig.base_confidence, 65.0);
        assert_eq!(sig.ticker_id, TickerId(42));
    }

    #[test]
    fn test_type_a_not_triggered_high_rsi() {
        // RSI too high (55 > 40)
        let signal = DipRecoveryDetector::detect(55.0, 2.0, 1.0, 2.5, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_a_not_triggered_low_volume() {
        // Volume not spiking enough (1.5 < 1.8x)
        let signal = DipRecoveryDetector::detect(35.0, 1.5, 1.0, 2.5, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_a_not_triggered_small_drop() {
        // Drop too small (1.5 < 2.0x ATR)
        let signal = DipRecoveryDetector::detect(35.0, 2.0, 1.0, 1.5, TickerId(42));
        assert!(signal.is_none());
    }
}

// ============================================================================
// Entry Type B: Early Runner (50 LOC)
// ============================================================================

/// Type B: Momentum building before overbought forms — YOUR EDGE.
/// Catches the uptrend before RSI hits 70.
pub struct EarlyRunnerDetector {
    rvol_history: VecDeque<f64>,
}

impl EarlyRunnerDetector {
    /// Create detector with empty history
    pub fn new() -> Self {
        Self {
            rvol_history: VecDeque::with_capacity(5),
        }
    }

    /// Detect Type B entry with configurable thresholds.
    pub fn detect_cfg(
        &mut self,
        current_rvol: f64,
        rsi: f64,
        ticker_id: TickerId,
        cfg: &EntryTypeConfig,
    ) -> Option<EntrySignal> {
        self.rvol_history.push_back(current_rvol);
        if self.rvol_history.len() > cfg.type_b_momentum_bars {
            self.rvol_history.pop_front();
        }

        if self.rvol_history.len() < cfg.type_b_momentum_bars {
            return None;
        }

        let vals: Vec<f64> = self.rvol_history.iter().copied().collect();
        let rising = vals.windows(2).all(|w| w[0] < w[1]);

        let trigger = rising
            && rsi > cfg.type_b_rsi_low && rsi < cfg.type_b_rsi_high;

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::EarlyRunner,
                base_confidence: cfg.type_b_confidence,
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }

    /// Legacy detect with hardcoded defaults.
    pub fn detect(
        &mut self,
        current_rvol: f64,
        rsi: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        self.detect_cfg(current_rvol, rsi, ticker_id, &EntryTypeConfig::default())
    }

    /// Reset history (useful for testing or ticker switch)
    pub fn reset(&mut self) {
        self.rvol_history.clear();
    }
}

impl Default for EarlyRunnerDetector {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod type_b_tests {
    use super::*;

    #[test]
    fn test_type_b_triggered_after_three_bars() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.2, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        let signal = detector.detect(1.8, 45.0, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::EarlyRunner);
        assert_eq!(sig.base_confidence, 82.0);
    }

    #[test]
    fn test_type_b_not_triggered_insufficient_bars() {
        let mut detector = EarlyRunnerDetector::new();
        let signal = detector.detect(1.5, 45.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_b_not_triggered_rvol_not_rising() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.8, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        let signal = detector.detect(1.2, 45.0, TickerId(42));
        // RVOL declining (1.8 > 1.5 > 1.2 is decreasing)
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_b_not_triggered_rsi_overbought() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.2, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        let signal = detector.detect(1.8, 75.0, TickerId(42));
        // RSI 75 > 60 (overbought)
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_b_reset() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.2, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        detector.reset();
        assert_eq!(detector.rvol_history.len(), 0);
    }
}

// ============================================================================
// Entry Type C: Overbought Fade (40 LOC)
// ============================================================================

/// Type C: Short overbought via inverse ETPs when price-volume divergence appears.
/// Catches reversal when strong price moves but volume declining.
pub struct OverboughtFadeDetector;

impl OverboughtFadeDetector {
    /// Detect Type C entry: Overbought + divergence (price up, volume down)
    /// Triggers when:
    /// - RSI > 75 (overbought, ready to pull back)
    /// - Volume divergence confirmed (price rising but volume declining)
    ///   Base confidence: 72%
    ///
    /// Note: volume_divergence_confirmed should be pre-calculated
    /// (price_pct_change > 0 AND volume < vol_ma20)
    pub fn detect_cfg(
        rsi: f64,
        vol_divergence_confirmed: bool,
        ticker_id: TickerId,
        cfg: &EntryTypeConfig,
    ) -> Option<EntrySignal> {
        let trigger = rsi > cfg.type_c_rsi_overbought && vol_divergence_confirmed;

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::OverboughtFade,
                base_confidence: cfg.type_c_confidence,
                ticker_id,
                side: Direction::Long,  // Actual trade would be SHORT via inverse ETP
                strategy: StrategyId::ApexScout,
            })
        } else {
            None
        }
    }

    /// Legacy detect with hardcoded defaults.
    pub fn detect(
        rsi: f64,
        vol_divergence_confirmed: bool,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        Self::detect_cfg(rsi, vol_divergence_confirmed, ticker_id, &EntryTypeConfig::default())
    }
}

#[cfg(test)]
mod type_c_tests {
    use super::*;

    #[test]
    fn test_type_c_triggered() {
        let signal = OverboughtFadeDetector::detect(78.0, true, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::OverboughtFade);
        assert_eq!(sig.base_confidence, 72.0);
    }

    #[test]
    fn test_type_c_not_triggered_no_divergence() {
        let signal = OverboughtFadeDetector::detect(78.0, false, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_c_not_triggered_low_rsi() {
        let signal = OverboughtFadeDetector::detect(70.0, true, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_c_borderline_rsi() {
        let signal = OverboughtFadeDetector::detect(75.1, true, TickerId(42));
        assert!(signal.is_some());
    }
}

// ============================================================================
// Entry Type D: Support Bounce (30 LOC)
// ============================================================================

/// Type D: Daily low bounce when price bounces back to support level.
/// Safest entry: buying right at support with RSI confirmation.
pub struct SupportBounceDetector;

impl SupportBounceDetector {
    /// Detect Type D entry: Price near daily low + RSI oversold
    /// Triggers when:
    /// - Current price within 1% of daily low
    /// - RSI 20-40 (panic oversold, recovery possible)
    ///   Base confidence: 70%
    pub fn detect_cfg(
        current_price: f64,
        daily_low: f64,
        rsi: f64,
        ticker_id: TickerId,
        cfg: &EntryTypeConfig,
    ) -> Option<EntrySignal> {
        if daily_low <= 0.0 {
            return None;
        }

        let price_pct_above_low = ((current_price - daily_low) / daily_low) * 100.0;
        let trigger = price_pct_above_low <= cfg.type_d_price_proximity_pct
            && rsi >= cfg.type_d_rsi_low && rsi <= cfg.type_d_rsi_high;

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::SupportBounce,
                base_confidence: cfg.type_d_confidence,
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }

    /// Legacy detect with hardcoded defaults.
    pub fn detect(
        current_price: f64,
        daily_low: f64,
        rsi: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        Self::detect_cfg(current_price, daily_low, rsi, ticker_id, &EntryTypeConfig::default())
    }
}

#[cfg(test)]
mod type_d_tests {
    use super::*;

    #[test]
    fn test_type_d_triggered() {
        let signal = SupportBounceDetector::detect(101.0, 100.0, 35.0, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::SupportBounce);
        assert_eq!(sig.base_confidence, 70.0);
    }

    #[test]
    fn test_type_d_triggered_exact_low() {
        let signal = SupportBounceDetector::detect(100.0, 100.0, 35.0, TickerId(42));
        assert!(signal.is_some());
    }

    #[test]
    fn test_type_d_not_triggered_too_far_from_low() {
        let signal = SupportBounceDetector::detect(102.0, 100.0, 35.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_d_not_triggered_rsi_too_high() {
        let signal = SupportBounceDetector::detect(101.0, 100.0, 50.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_d_not_triggered_rsi_too_low() {
        let signal = SupportBounceDetector::detect(101.0, 100.0, 15.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_d_invalid_daily_low() {
        let signal = SupportBounceDetector::detect(101.0, 0.0, 35.0, TickerId(42));
        assert!(signal.is_none());
    }
}

// ============================================================================
// Entry Type E: IBS Mean Reversion (Sprint B)
// ============================================================================

/// Type E: IBS Mean Reversion — buy when Internal Bar Strength near zero in
/// mean-reverting regime with elevated RVOL. IBS = (Close - Low) / (High - Low).
/// IBS < threshold signals extreme selling pressure, likely to revert.
pub struct IBSMeanReversionDetector;

impl IBSMeanReversionDetector {
    /// Detect Type E entry with configurable thresholds.
    /// Triggers when:
    /// - IBS < type_e_ibs_threshold (default 0.10)
    /// - RVOL > type_e_rvol_threshold (default 1.0)
    /// - Regime is mean_reverting (caller must verify)
    pub fn detect_cfg(
        ibs: f64,
        rvol: f64,
        ticker_id: TickerId,
        cfg: &EntryTypeConfig,
    ) -> Option<EntrySignal> {
        let trigger = ibs < cfg.type_e_ibs_threshold
            && rvol > cfg.type_e_rvol_threshold;

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::IBSMeanReversion,
                base_confidence: cfg.type_e_confidence,
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }

    /// Legacy detect with hardcoded defaults.
    pub fn detect(
        ibs: f64,
        rvol: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        Self::detect_cfg(ibs, rvol, ticker_id, &EntryTypeConfig::default())
    }
}

#[cfg(test)]
mod type_e_tests {
    use super::*;

    #[test]
    fn test_type_e_triggered() {
        let signal = IBSMeanReversionDetector::detect(0.05, 1.5, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::IBSMeanReversion);
        assert_eq!(sig.base_confidence, 70.0);
    }

    #[test]
    fn test_type_e_not_triggered_high_ibs() {
        let signal = IBSMeanReversionDetector::detect(0.20, 1.5, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_e_not_triggered_low_rvol() {
        let signal = IBSMeanReversionDetector::detect(0.05, 0.8, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_e_borderline_ibs() {
        // IBS exactly at threshold — should NOT trigger (< not <=)
        let signal = IBSMeanReversionDetector::detect(0.10, 1.5, TickerId(42));
        assert!(signal.is_none());
    }
}

// ============================================================================
// Entry Type F: OBV Divergence (Sprint E)
// ============================================================================

/// Type F: OBV Divergence — buy when OBV-RSI is deeply oversold, indicating
/// volume-weighted selling pressure diverging from price. OBV-RSI is the RSI
/// computed on the On-Balance Volume series. Low OBV-RSI with moderate RVOL
/// signals accumulation beneath the surface.
pub struct OBVDivergenceDetector;

impl OBVDivergenceDetector {
    /// Detect Type F entry with configurable thresholds.
    /// Triggers when:
    /// - OBV-RSI < type_f_obv_rsi_threshold (default 30.0)
    /// - RVOL > type_f_rvol_threshold (default 0.7)
    pub fn detect_cfg(
        obv_rsi: f64,
        rvol: f64,
        ticker_id: TickerId,
        cfg: &EntryTypeConfig,
    ) -> Option<EntrySignal> {
        let trigger = obv_rsi < cfg.type_f_obv_rsi_threshold
            && rvol > cfg.type_f_rvol_threshold;

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::OBVDivergence,
                base_confidence: cfg.type_f_confidence,
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }

    /// Legacy detect with hardcoded defaults.
    pub fn detect(
        obv_rsi: f64,
        rvol: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        Self::detect_cfg(obv_rsi, rvol, ticker_id, &EntryTypeConfig::default())
    }
}

#[cfg(test)]
mod type_f_tests {
    use super::*;

    #[test]
    fn test_type_f_triggered() {
        let signal = OBVDivergenceDetector::detect(20.0, 1.0, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::OBVDivergence);
        assert_eq!(sig.base_confidence, 68.0);
    }

    #[test]
    fn test_type_f_not_triggered_high_obv_rsi() {
        let signal = OBVDivergenceDetector::detect(35.0, 1.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_f_not_triggered_low_rvol() {
        let signal = OBVDivergenceDetector::detect(20.0, 0.5, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_f_borderline_obv_rsi() {
        // OBV-RSI exactly at threshold — should NOT trigger (< not <=)
        let signal = OBVDivergenceDetector::detect(30.0, 1.0, TickerId(42));
        assert!(signal.is_none());
    }
}

// ============================================================================
// Tier-Based Entry Type Selection (10 LOC)
// ============================================================================

/// Trading tier classification
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    /// Tier One: Conservative, support bounces only
    One,
    /// Tier Two: Moderate, all 4 entry types allowed
    Two,
    /// Tier Three: Aggressive, momentum + fade only
    Three,
    /// Tier Four: Dormant, no trading
    Four,
}

/// Select which entry types are available for a given tier
pub fn select_entry_types_by_tier(tier: Tier) -> &'static [EntryType] {
    match tier {
        Tier::One => &[EntryType::SupportBounce],  // Safest
        Tier::Two => &[
            EntryType::DipRecovery,
            EntryType::EarlyRunner,
            EntryType::OverboughtFade,
            EntryType::SupportBounce,
            EntryType::IBSMeanReversion,
            EntryType::OBVDivergence,
        ],
        Tier::Three => &[EntryType::EarlyRunner, EntryType::OverboughtFade],  // Aggressive
        Tier::Four => &[],  // No trading
    }
}

#[cfg(test)]
mod tier_tests {
    use super::*;

    #[test]
    fn test_tier_one_conservative() {
        let types = select_entry_types_by_tier(Tier::One);
        assert_eq!(types.len(), 1);
        assert_eq!(types[0], EntryType::SupportBounce);
    }

    #[test]
    fn test_tier_two_moderate() {
        let types = select_entry_types_by_tier(Tier::Two);
        assert_eq!(types.len(), 6);
        assert!(types.contains(&EntryType::DipRecovery));
        assert!(types.contains(&EntryType::EarlyRunner));
        assert!(types.contains(&EntryType::IBSMeanReversion));
        assert!(types.contains(&EntryType::OBVDivergence));
    }

    #[test]
    fn test_tier_three_aggressive() {
        let types = select_entry_types_by_tier(Tier::Three);
        assert_eq!(types.len(), 2);
        assert!(types.contains(&EntryType::EarlyRunner));
        assert!(types.contains(&EntryType::OverboughtFade));
    }

    #[test]
    fn test_tier_four_dormant() {
        let types = select_entry_types_by_tier(Tier::Four);
        assert!(types.is_empty());
    }
}

// ============================================================================
// Confidence Decay (10 LOC)
// ============================================================================

/// Apply time-based confidence decay to entry signal.
/// Confidence degrades at 2.1% per hour held.
/// Entry loses edge as opportunity window closes.
/// Sprint 6: Configurable decay rate.
pub fn apply_confidence_decay_cfg(base_confidence: f64, hours_held: f64, decay_rate: f64) -> f64 {
    let decayed = base_confidence - (decay_rate * hours_held);
    decayed.max(0.0)
}

/// Legacy: backward compat with hardcoded 2.1% per hour.
pub fn apply_confidence_decay(base_confidence: f64, hours_held: f64) -> f64 {
    apply_confidence_decay_cfg(base_confidence, hours_held, 2.1)
}

#[cfg(test)]
mod decay_tests {
    use super::*;

    #[test]
    fn test_confidence_no_decay_fresh() {
        assert_eq!(apply_confidence_decay(82.0, 0.0), 82.0);
    }

    #[test]
    fn test_confidence_decays_one_hour() {
        let result = apply_confidence_decay(82.0, 1.0);
        assert!((result - 79.9).abs() < 0.01);
    }

    #[test]
    fn test_confidence_decays_multiple_hours() {
        let result = apply_confidence_decay(82.0, 5.0);
        assert!((result - 71.5).abs() < 0.01);
    }

    #[test]
    fn test_confidence_clamped_at_zero() {
        let result = apply_confidence_decay(82.0, 40.0);
        assert_eq!(result, 0.0);
    }

    #[test]
    fn test_confidence_decay_various_bases() {
        assert!((apply_confidence_decay(65.0, 10.0) - 44.0).abs() < 0.01);
        assert!((apply_confidence_decay(72.0, 15.0) - 40.5).abs() < 0.01);
    }
}
