//! Entry signal generation with 4 entry types, tier routing, and confidence decay.
//! Type A (40 LOC) + Type B (50 LOC) + Type C (40 LOC) + Type D (30 LOC)
//! Tier routing + Confidence decay (20 LOC)

use crate::types::{Direction, StrategyId, TickerId};
use std::collections::VecDeque;

// ============================================================================
// Entry Signal Types & Base Structure (40 LOC)
// ============================================================================

/// Entry signal classification
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntryType {
    /// Type A: Support bounce from recent lows (65% base confidence)
    DipRecovery,
    /// Type B: Momentum before overbought forms — YOUR EDGE (82% base confidence)
    EarlyRunner,
    /// Type C: Shorting via inverse ETPs (72% base confidence)
    OverboughtFade,
    /// Type D: Daily low bounce (70% base confidence)
    SupportBounce,
}

/// Entry signal generated by any entry detector
#[derive(Debug, Clone)]
pub struct EntrySignal {
    /// Which entry type triggered
    pub entry_type: EntryType,
    /// Base confidence before decay [0.0, 100.0]
    pub base_confidence: f64,
    /// Interned ticker ID for this entry
    pub ticker_id: TickerId,
    /// Direction (Long only in ISA)
    pub side: Direction,
    /// Strategy that generated this
    pub strategy: StrategyId,
}

impl EntrySignal {
    /// Create a new entry signal with all required fields
    pub fn new(
        entry_type: EntryType,
        base_confidence: f64,
        ticker_id: TickerId,
        side: Direction,
        strategy: StrategyId,
    ) -> Self {
        Self {
            entry_type,
            base_confidence: base_confidence.clamp(0.0, 100.0),
            ticker_id,
            side,
            strategy,
        }
    }
}

// ============================================================================
// Entry Type A: Dip Recovery (40 LOC)
// ============================================================================

/// Type A: Price drops 2+ ATR from recent high, RSI oversold, volume expanding.
/// Entry logic: Buy the dip when volatility spike + weak hands panic.
pub struct DipRecoveryDetector;

impl DipRecoveryDetector {
    /// Detect Type A entry: Oversold dip with volume expansion
    /// Triggers when:
    /// - RSI < 40 (oversold)
    /// - Volume expansion > 1.8x MA (fear spike)
    /// - Price drop >= 2.0x ATR (significant decline)
    /// Base confidence: 65%
    pub fn detect(
        rsi: f64,
        rvol: f64,
        vol_ma20: f64,
        price_drop_atr_multiple: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        // All three conditions must be met
        let trigger = rsi < 40.0                      // Oversold panic
            && rvol > vol_ma20 * 1.8                 // Volume spike on decline
            && price_drop_atr_multiple >= 2.0;       // Significant drop (2+ ATR)

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::DipRecovery,
                base_confidence: 65.0,
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }
}

#[cfg(test)]
mod type_a_tests {
    use super::*;

    #[test]
    fn test_type_a_triggered_all_conditions_met() {
        let signal = DipRecoveryDetector::detect(35.0, 2.0, 1.0, 2.5, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::DipRecovery);
        assert_eq!(sig.base_confidence, 65.0);
        assert_eq!(sig.ticker_id, TickerId(42));
    }

    #[test]
    fn test_type_a_not_triggered_high_rsi() {
        // RSI too high (55 > 40)
        let signal = DipRecoveryDetector::detect(55.0, 2.0, 1.0, 2.5, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_a_not_triggered_low_volume() {
        // Volume not spiking enough (1.5 < 1.8x)
        let signal = DipRecoveryDetector::detect(35.0, 1.5, 1.0, 2.5, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_a_not_triggered_small_drop() {
        // Drop too small (1.5 < 2.0x ATR)
        let signal = DipRecoveryDetector::detect(35.0, 2.0, 1.0, 1.5, TickerId(42));
        assert!(signal.is_none());
    }
}

// ============================================================================
// Entry Type B: Early Runner (50 LOC)
// ============================================================================

/// Type B: Momentum building before overbought forms — YOUR EDGE.
/// Catches the uptrend before RSI hits 70.
pub struct EarlyRunnerDetector {
    rvol_history: VecDeque<f64>,
}

impl EarlyRunnerDetector {
    /// Create detector with empty history
    pub fn new() -> Self {
        Self {
            rvol_history: VecDeque::with_capacity(5),
        }
    }

    /// Detect Type B entry: Momentum building + not overbought yet
    /// Triggers when:
    /// - Last 3 bars: RVOL rising (momentum confirmed)
    /// - Current RSI 30-60 (early, not overbought yet)
    /// Base confidence: 82% (YOUR EDGE)
    ///
    /// Note: Must call detect() 3+ times before triggering (needs history).
    pub fn detect(
        &mut self,
        current_rvol: f64,
        rsi: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        // Track last 3 RVOL values for trend
        self.rvol_history.push_back(current_rvol);
        if self.rvol_history.len() > 3 {
            self.rvol_history.pop_front();
        }

        // Need 3 bars to confirm uptrend
        if self.rvol_history.len() < 3 {
            return None;
        }

        let vals: Vec<f64> = self.rvol_history.iter().copied().collect();
        let rising = vals[0] < vals[1] && vals[1] < vals[2];

        let trigger = rising                        // RVOL rising (momentum confirmed)
            && rsi > 30.0 && rsi < 70.0;           // AUDIT-FIX: raised ceiling 60→70 (was too tight, missed valid entries)
            // But still blocks overbought (RSI > 70) entries that chase extended moves

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::EarlyRunner,
                base_confidence: 82.0,  // YOUR EDGE
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }

    /// Reset history (useful for testing or ticker switch)
    pub fn reset(&mut self) {
        self.rvol_history.clear();
    }
}

impl Default for EarlyRunnerDetector {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod type_b_tests {
    use super::*;

    #[test]
    fn test_type_b_triggered_after_three_bars() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.2, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        let signal = detector.detect(1.8, 45.0, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::EarlyRunner);
        assert_eq!(sig.base_confidence, 82.0);
    }

    #[test]
    fn test_type_b_not_triggered_insufficient_bars() {
        let mut detector = EarlyRunnerDetector::new();
        let signal = detector.detect(1.5, 45.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_b_not_triggered_rvol_not_rising() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.8, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        let signal = detector.detect(1.2, 45.0, TickerId(42));
        // RVOL declining (1.8 > 1.5 > 1.2 is decreasing)
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_b_not_triggered_rsi_overbought() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.2, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        let signal = detector.detect(1.8, 75.0, TickerId(42));
        // RSI 75 > 60 (overbought)
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_b_reset() {
        let mut detector = EarlyRunnerDetector::new();
        detector.detect(1.2, 35.0, TickerId(42));
        detector.detect(1.5, 40.0, TickerId(42));
        detector.reset();
        assert_eq!(detector.rvol_history.len(), 0);
    }
}

// ============================================================================
// Entry Type C: Overbought Fade (40 LOC)
// ============================================================================

/// Type C: Short overbought via inverse ETPs when price-volume divergence appears.
/// Catches reversal when strong price moves but volume declining.
pub struct OverboughtFadeDetector;

impl OverboughtFadeDetector {
    /// Detect Type C entry: Overbought + divergence (price up, volume down)
    /// Triggers when:
    /// - RSI > 75 (overbought, ready to pull back)
    /// - Volume divergence confirmed (price rising but volume declining)
    /// Base confidence: 72%
    ///
    /// Note: volume_divergence_confirmed should be pre-calculated
    /// (price_pct_change > 0 AND volume < vol_ma20)
    pub fn detect(
        rsi: f64,
        vol_divergence_confirmed: bool,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        let trigger = rsi > 75.0 && vol_divergence_confirmed;

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::OverboughtFade,
                base_confidence: 72.0,
                ticker_id,
                side: Direction::Long,  // Actual trade would be SHORT via inverse ETP
                strategy: StrategyId::ApexScout,
            })
        } else {
            None
        }
    }
}

#[cfg(test)]
mod type_c_tests {
    use super::*;

    #[test]
    fn test_type_c_triggered() {
        let signal = OverboughtFadeDetector::detect(78.0, true, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::OverboughtFade);
        assert_eq!(sig.base_confidence, 72.0);
    }

    #[test]
    fn test_type_c_not_triggered_no_divergence() {
        let signal = OverboughtFadeDetector::detect(78.0, false, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_c_not_triggered_low_rsi() {
        let signal = OverboughtFadeDetector::detect(70.0, true, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_c_borderline_rsi() {
        let signal = OverboughtFadeDetector::detect(75.1, true, TickerId(42));
        assert!(signal.is_some());
    }
}

// ============================================================================
// Entry Type D: Support Bounce (30 LOC)
// ============================================================================

/// Type D: Daily low bounce when price bounces back to support level.
/// Safest entry: buying right at support with RSI confirmation.
pub struct SupportBounceDetector;

impl SupportBounceDetector {
    /// Detect Type D entry: Price near daily low + RSI oversold
    /// Triggers when:
    /// - Current price within 1% of daily low
    /// - RSI 20-40 (panic oversold, recovery possible)
    /// Base confidence: 70%
    pub fn detect(
        current_price: f64,
        daily_low: f64,
        rsi: f64,
        ticker_id: TickerId,
    ) -> Option<EntrySignal> {
        // Calculate how far above daily low
        if daily_low <= 0.0 {
            return None; // Invalid daily low
        }

        let price_pct_above_low = ((current_price - daily_low) / daily_low) * 100.0;
        let trigger = price_pct_above_low <= 1.0 // Within 1% of daily low
            && rsi >= 20.0 && rsi <= 40.0;       // Oversold but recovering

        if trigger {
            Some(EntrySignal {
                entry_type: EntryType::SupportBounce,
                base_confidence: 70.0,
                ticker_id,
                side: Direction::Long,
                strategy: StrategyId::VanguardSniper,
            })
        } else {
            None
        }
    }
}

#[cfg(test)]
mod type_d_tests {
    use super::*;

    #[test]
    fn test_type_d_triggered() {
        let signal = SupportBounceDetector::detect(101.0, 100.0, 35.0, TickerId(42));
        assert!(signal.is_some());
        let sig = signal.unwrap();
        assert_eq!(sig.entry_type, EntryType::SupportBounce);
        assert_eq!(sig.base_confidence, 70.0);
    }

    #[test]
    fn test_type_d_triggered_exact_low() {
        let signal = SupportBounceDetector::detect(100.0, 100.0, 35.0, TickerId(42));
        assert!(signal.is_some());
    }

    #[test]
    fn test_type_d_not_triggered_too_far_from_low() {
        let signal = SupportBounceDetector::detect(102.0, 100.0, 35.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_d_not_triggered_rsi_too_high() {
        let signal = SupportBounceDetector::detect(101.0, 100.0, 50.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_d_not_triggered_rsi_too_low() {
        let signal = SupportBounceDetector::detect(101.0, 100.0, 15.0, TickerId(42));
        assert!(signal.is_none());
    }

    #[test]
    fn test_type_d_invalid_daily_low() {
        let signal = SupportBounceDetector::detect(101.0, 0.0, 35.0, TickerId(42));
        assert!(signal.is_none());
    }
}

// ============================================================================
// Tier-Based Entry Type Selection (10 LOC)
// ============================================================================

/// Trading tier classification
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    /// Tier One: Conservative, support bounces only
    One,
    /// Tier Two: Moderate, all 4 entry types allowed
    Two,
    /// Tier Three: Aggressive, momentum + fade only
    Three,
    /// Tier Four: Dormant, no trading
    Four,
}

/// Select which entry types are available for a given tier
pub fn select_entry_types_by_tier(tier: Tier) -> &'static [EntryType] {
    match tier {
        Tier::One => &[EntryType::SupportBounce],  // Safest
        Tier::Two => &[
            EntryType::DipRecovery,
            EntryType::EarlyRunner,
            EntryType::OverboughtFade,
            EntryType::SupportBounce,
        ],
        Tier::Three => &[EntryType::EarlyRunner, EntryType::OverboughtFade],  // Aggressive
        Tier::Four => &[],  // No trading
    }
}

#[cfg(test)]
mod tier_tests {
    use super::*;

    #[test]
    fn test_tier_one_conservative() {
        let types = select_entry_types_by_tier(Tier::One);
        assert_eq!(types.len(), 1);
        assert_eq!(types[0], EntryType::SupportBounce);
    }

    #[test]
    fn test_tier_two_moderate() {
        let types = select_entry_types_by_tier(Tier::Two);
        assert_eq!(types.len(), 4);
        assert!(types.contains(&EntryType::DipRecovery));
        assert!(types.contains(&EntryType::EarlyRunner));
    }

    #[test]
    fn test_tier_three_aggressive() {
        let types = select_entry_types_by_tier(Tier::Three);
        assert_eq!(types.len(), 2);
        assert!(types.contains(&EntryType::EarlyRunner));
        assert!(types.contains(&EntryType::OverboughtFade));
    }

    #[test]
    fn test_tier_four_dormant() {
        let types = select_entry_types_by_tier(Tier::Four);
        assert!(types.is_empty());
    }
}

// ============================================================================
// Confidence Decay (10 LOC)
// ============================================================================

/// Apply time-based confidence decay to entry signal.
/// Confidence degrades at 2.1% per hour held.
/// Entry loses edge as opportunity window closes.
pub fn apply_confidence_decay(base_confidence: f64, hours_held: f64) -> f64 {
    let decay_rate = 2.1;  // % per hour
    let decayed = base_confidence - (decay_rate * hours_held);
    decayed.max(0.0)  // Clamp at 0 (no negative confidence)
}

#[cfg(test)]
mod decay_tests {
    use super::*;

    #[test]
    fn test_confidence_no_decay_fresh() {
        assert_eq!(apply_confidence_decay(82.0, 0.0), 82.0);
    }

    #[test]
    fn test_confidence_decays_one_hour() {
        let result = apply_confidence_decay(82.0, 1.0);
        assert!((result - 79.9).abs() < 0.01);
    }

    #[test]
    fn test_confidence_decays_multiple_hours() {
        let result = apply_confidence_decay(82.0, 5.0);
        assert!((result - 71.5).abs() < 0.01);
    }

    #[test]
    fn test_confidence_clamped_at_zero() {
        let result = apply_confidence_decay(82.0, 40.0);
        assert_eq!(result, 0.0);
    }

    #[test]
    fn test_confidence_decay_various_bases() {
        assert!((apply_confidence_decay(65.0, 10.0) - 44.0).abs() < 0.01);
        assert!((apply_confidence_decay(72.0, 15.0) - 40.5).abs() < 0.01);
    }
}
