#!/usr/bin/env bash
# AEGIS Plan Sync Script
# Combines all split .md files into AEGIS_COMPLETE.md and generates PDF
# Run from the aegis/ directory or provide path as argument
#
# Usage: bash aegis/sync.sh
#        bash aegis/sync.sh --no-pdf   (skip PDF generation)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

NO_PDF=false
if [[ "${1:-}" == "--no-pdf" ]]; then
    NO_PDF=true
fi

COMBINED="AEGIS_COMPLETE.md"
PDF_FILE="AEGIS_COMPLETE.pdf"

# Ordered list of split files
FILES=(
    "01_STOP_SHIP.md"
    "02_STRATEGY.md"
    "03_EXECUTION_TIMING.md"
    "04_HARDENING.md"
    "05_QUANTUM_APEX.md"
    "06_EXECUTIONER.md"
    "07_RISK.md"
    "08_INFRASTRUCTURE.md"
    "09_IMPLEMENTATION.md"
    "10_APPENDIX.md"
)

echo "=== AEGIS Sync ==="
echo "Combining ${#FILES[@]} files into $COMBINED..."

# Check all files exist
MISSING=0
for f in "${FILES[@]}"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Missing file: $f"
        MISSING=$((MISSING + 1))
    fi
done

if [[ $MISSING -gt 0 ]]; then
    echo "ABORT: $MISSING file(s) missing. Fix before syncing."
    exit 1
fi

# Build combined file
{
    echo "# AEGIS ALPHA-OMEGA MASTER PLAN v16.2"
    echo "## UK ISA Momentum-Volatility Intelligence Engine — COMPLETE"
    echo "### NZT-48 → Leveraged ETP Compounding Machine"
    echo ""
    echo "> **Auto-generated** by \`aegis/sync.sh\` on $(date '+%Y-%m-%d %H:%M:%S')"
    echo "> Do NOT edit this file directly — edit the individual section files instead."
    echo "> Run \`bash aegis/sync.sh\` to regenerate after changes."
    echo ""
    echo "---"
    echo ""

    # Table of contents from file titles
    echo "## Document Index"
    echo ""
    echo "| # | File | Description |"
    echo "|---|------|-------------|"
    for f in "${FILES[@]}"; do
        # Extract first heading
        TITLE=$(head -1 "$f" | sed 's/^# AEGIS — //' | sed 's/^# //')
        NUM=$(echo "$f" | sed 's/_.*//' | sed 's/^0//')
        echo "| $NUM | [$f](#${f%.md}) | $TITLE |"
    done
    echo ""
    echo "---"
    echo ""

    # Concatenate all files with separators
    for f in "${FILES[@]}"; do
        echo ""
        echo "<!-- ========== $f ========== -->"
        echo ""
        cat "$f"
        echo ""
        echo ""
        echo "---"
        echo ""
    done
} > "$COMBINED"

LINES=$(wc -l < "$COMBINED")
SIZE=$(du -h "$COMBINED" | cut -f1)
echo "Combined: $COMBINED ($LINES lines, $SIZE)"

# Generate PDF if not skipped
if [[ "$NO_PDF" == false ]]; then
    echo "Generating PDF..."

    if python3 -c "import fitz; import markdown" 2>/dev/null; then
        # Use PyMuPDF (fitz.Story) + markdown for PDF generation
        python3 -c "
import markdown
import fitz
import sys

with open('$COMBINED', 'r') as f:
    md_content = f.read()

html = markdown.markdown(md_content, extensions=['tables', 'fenced_code', 'toc'])

styled_html = '''<!DOCTYPE html>
<html>
<head>
<meta charset=\"utf-8\">
<style>
    body { font-family: Helvetica, Arial, sans-serif;
           font-size: 10px; line-height: 1.4; color: #24292e; }
    h1 { font-size: 20px; border-bottom: 2px solid #c9d1d9; padding-bottom: 6px; margin-top: 24px; }
    h2 { font-size: 16px; border-bottom: 1px solid #d0d7de; padding-bottom: 4px; margin-top: 20px; }
    h3 { font-size: 13px; margin-top: 16px; }
    h4 { font-size: 11px; margin-top: 12px; }
    table { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 9px; }
    th, td { border: 1px solid #d0d7de; padding: 4px 6px; text-align: left; }
    th { background: #f6f8fa; font-weight: bold; }
    code { background: #f6f8fa; padding: 1px 3px; font-size: 9px; }
    pre { background: #f6f8fa; padding: 8px; }
    blockquote { border-left: 3px solid #d0d7de; margin: 0; padding: 2px 12px; color: #57606a; }
    hr { border: none; border-top: 1px solid #d0d7de; margin: 16px 0; }
    strong { color: #1f2328; }
</style>
</head>
<body>
''' + html + '''
</body>
</html>'''

# Use fitz.Story to render HTML to PDF
MEDIABOX = fitz.paper_rect('a4')
WHERE = MEDIABOX + fitz.Rect(36, 36, -36, -36)  # 0.5 inch margins

story = fitz.Story(styled_html)
writer = fitz.DocumentWriter('$PDF_FILE')

more = True
while more:
    dev = writer.begin_page(MEDIABOX)
    more, _ = story.place(WHERE)
    story.draw(dev)
    writer.end_page()

writer.close()

# Add page numbers
doc = fitz.open('$PDF_FILE')
for i, page in enumerate(doc):
    rect = fitz.Rect(0, page.rect.height - 30, page.rect.width, page.rect.height)
    page.insert_textbox(rect, f'Page {i+1} of {len(doc)}', fontsize=8, align=fitz.TEXT_ALIGN_CENTER, color=(0.4, 0.4, 0.4))
doc.save('$PDF_FILE', incremental=True, encryption=0)
doc.close()

print(f'PDF generated: $PDF_FILE ({len(fitz.open(\"$PDF_FILE\"))} pages)')
" 2>&1
        if [[ $? -eq 0 ]]; then
            PDF_SIZE=$(du -h "$PDF_FILE" | cut -f1)
            echo "PDF: $PDF_FILE ($PDF_SIZE)"
        else
            echo "WARNING: PDF generation failed. Combined .md still created."
        fi
    else
        echo "WARNING: No PDF generator found. Install: pip3 install PyMuPDF markdown"
        echo "Combined .md file created successfully."
    fi
else
    echo "PDF generation skipped (--no-pdf flag)"
fi

echo ""
echo "=== Sync Complete ==="
echo "Files: ${#FILES[@]} sections + $COMBINED"
echo "Lines: $LINES"
