"""Build a 2500-ticker universe from full index constituent lists.

Uses IBKR contract search (reqMatchingSymbols) AND explicit lists so we
don't rely on guesses. Runs end-to-end in one go.
"""
from __future__ import annotations

import asyncio
import logging
from collections import Counter
from pathlib import Path

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s")

OUT = Path("/Users/rr/aegis-v5/data/universe_2500.toml")


# Full S&P 500 (as of ~2025; static copy to avoid extra API call)
SP500 = """A AAL AAP AAPL ABBV ABC ABMD ABNB ABT ACGL ACN ADBE ADI ADM ADP ADSK
AEE AEP AES AFL AIG AIZ AJG AKAM ALB ALGN ALK ALL ALLE AMAT AMCR AMD AME AMGN
AMP AMT AMZN ANET ANSS AON AOS APA APD APH APTV ARE ATO ATVI AVB AVGO AVY AWK
AXON AXP AZO BA BAC BALL BAX BBWI BBY BDX BEN BF.B BG BIIB BIO BK BKNG BKR BLK
BMY BR BRK.B BRO BSX BWA BXP C CAG CAH CARR CAT CB CBOE CBRE CCI CCL CDAY CDNS
CDW CE CEG CERN CF CFG CHD CHRW CHTR CI CINF CL CLX CMA CMCSA CME CMG CMI CMS
CNC CNP COF COO COP COST CPB CPRT CRL CRM CSCO CSGP CSX CTAS CTLT CTRA CTSH CTVA
CTXS CVS CVX CZR D DAL DD DE DFS DG DGX DHI DHR DIS DISCA DISCK DISH DLR DLTR DOV
DOW DPZ DRE DRI DTE DUK DVA DVN DXC DXCM EA EBAY ECL ED EFX EIX EL ELV EMN EMR ENPH
EOG EPAM EQIX EQR EQT ES ESS ETN ETR ETSY EVRG EW EXC EXPD EXPE EXR F FANG FAST FB
FBHS FCX FDS FDX FE FFIV FIS FISV FITB FLT FMC FOX FOXA FRC FRT FTI FTNT FTV GD GE
GEHC GEN GILD GIS GL GLW GM GNRC GOOG GOOGL GPC GPN GRMN GS GWW HAL HAS HBAN HCA HD
HES HIG HII HOLX HON HPE HPQ HRL HSIC HST HSY HUM HWM IBM ICE IDXX IEX IFF ILMN INCY
INFO INTC INTU INVH IP IPG IQV IR IRM ISRG IT ITW IVZ J JBHT JCI JKHY JNJ JNPR JPM K
KDP KEY KEYS KHC KIM KLAC KMB KMI KMX KO KR KSU L LDOS LEG LEN LH LHX LIN LKQ LLY LMT
LNC LNT LOW LRCX LUMN LUV LVS LW LYB LYV MA MAA MAR MAS MCD MCHP MCK MCO MDLZ MDT MET
META MGM MHK MKC MKTX MLM MMC MMM MNST MO MOH MOS MPC MPWR MRK MRNA MRO MS MSCI MSFT
MSI MTB MTCH MTD MU NCLH NDAQ NDSN NEE NEM NFLX NI NKE NLOK NLSN NOC NOW NRG NSC NTAP
NTRS NUE NVDA NVR NWL NWS NWSA NXPI O ODFL OGN OKE OMC ORCL ORLY OTIS OXY PAYC PAYX PCAR
PCG PEAK PEG PEP PFE PFG PG PGR PH PHM PKG PKI PLD PM PNC PNR PNW POOL PPG PPL PRU PSA
PSX PTC PVH PWR PXD PYPL QCOM QRVO RCL RE REG REGN RF RHI RJF RL RMD ROK ROL ROP ROST
RSG RTX SBAC SBNY SBUX SCHW SEDG SEE SHW SIVB SJM SLB SNA SNPS SO SPG SPGI SRE STE STLD
STT STX STZ SWK SWKS SYF SYK SYY T TAP TDG TDY TECH TEL TER TFC TFX TGT TJX TMO TMUS TPG
TPR TRGP TRMB TROW TRV TSCO TSLA TSN TT TTWO TWTR TXN TXT TYL UA UAA UAL UDR UHS ULTA UNH
UNP UPS URI USB V VFC VICI VLO VMC VNO VRSK VRSN VRTX VTR VTRS V WAB WAT WBA WBD WDC WEC
WELL WFC WHR WM WMB WMT WRB WRK WST WTW WY WYNN XEL XOM XRAY XYL YUM ZBH ZBRA ZION ZTS"""

# Russell 1000 additional (not in S&P 500)
RUSSELL1000_ADDITIONAL = """AAON ABG ABM ACAD ACIW ACM ACN ADC ADTN AEIS AFG AGO AIT AIZN
ALE ALIT ALKS ALLY ALSN AMBA AMBP AMCX AMED AMKR AMWD AN ANF AOS APAM APG APLE APLS APP APPF
APPN APTV ARCB ARCH ARCO ARES ARI ARMK ARNC ARWR ASAN ASB ASH ATI ATR ATUS AUB AUR AVA AVNT
AVTR AWI AX AYI AZEK AZTA AZZ BANC BANF BANR BATRA BATRK BAX BC BCC BCO BCPC BCRX BDC BDN
BE BECN BEKE BELFB BEN BERY BFAM BFC BG BGS BHC BHE BHF BHG BIIB BILL BIO BIPC BJ BKE BKH
BKI BKU BLD BLKB BLMN BMI BMRN BOH BOOT BOX BPMC BPT BRBR BRC BRKR BRO BRT BRX BSIG BSY
BTU BUD BV BVN BWA BXMT BYD BYND CACC CACI CAH CAL CALM CALX CAMT CAR CARG CARR CARS CASH
CAT CATO CBD CBRL CBSH CBT CC CCB CCEP CCI CCK CCL CCOI CCRN CDE CDNA CDW CEIX CELH CENT
CENTA CENX CEQP CERE CERT CEVA CFG CFR CHDN CHE CHEF CHKP CHRD CHRW CHS CHUY CHWY CHX CIA
CIEN CIR CLB CLFD CLH CLMT CLVT CLX CMA CMC CMCO CMP CMRE CNC CNHI CNI CNK CNMD CNOB CNP
CNS CNX COHR COHU COKE COLB COLM COMM COOP COR CORT COUR COWN CPA CPB CPE CPK CPRI CPRT
CPT CR CRBG CRI CRL CRNX CROX CRS CRSR CRUS CRVL CRWD CSGP CSII CSIQ CSL CSOD CSTM CSV CSWI
CSX CTAS CTBI CTLT CTOS CTRE CTRN CTS CTSH CTVA CUBE CUTR CVA CVBF CVCO CVET CVEO CVGW CVI
CVLT CVNA CVS CW CWCO CWEN CWH CWK CXP CYBR DAL DAN DAR DASH DBD DBI DCI DCO DDD DDOG DDS
DE DECK DEI DELL DFIN DFS DHR DIN DINO DIOD DIS DK DKL DKS DLB DLR DLTR DNB DNOW DNUT DOC
DOCS DOCU DORM DOV DOX DPZ DQ DRH DRI DRVN DSGX DSP DT DTC DTE DTM DUK DV DVA DVAX DVN DX
DXC DXCM DXPE DY EA EAF EAT EB EBAY EBC EBIX EBS ECHO ECL ED EDIT EEFT EEX EGBN EGP EGY EHC
EIX EL ELAN ELF ELMD ELS ELV ELVT EMN EMR EMX ENB ENLC ENOV ENPH ENR ENS ENTG ENV ENVA ENVX
ENZ EOG EPAC EPAM EPAY EPC EPM EPR EPRT EQBK EQC EQH EQIX EQNR EQR EQT ERIE ERII ES ESAB
ESAB ESE ESGR ESI ESS ESTC ESTE ET ETD ETN ETR ETRN ETSY ETWO EV EVBG EVC EVER EVH EVR
EVRI EVTC EW EWBC EWCZ EXAS EXC EXEL EXEL EXLS EXPD EXPI EXPO EXR EXTR EYE EZPW F FA FAF
FANG FAST FATE FBIN FBP FC FCEL FCF FCFS FCN FCNCA FCPT FCX FDP FDS FDX FE FELE FET FFBC
FFG FFIC FHN FHOLX FI FIBK FICO FINV FIS FISV FIVE FIVN FIX FIZZ FL FLEX FLGT FLL FLN
FLNC FLO FLR FLS FLT FLWS FLY FMC FMS FN FND FNF FNKO FOCS FOE FOLD FOR FORG FORM FORR
FOSL FOUR FOX FOXA FOXF FPH FR FRBK FRC FREY FRG FRGI FRME FRPT FRSH FRT FSLR FSLY FSS
FSV FTAI FTDR FTI FTNT FTV FTV FUBO FUL FULT FUN FWRG FWRD G GAP GATX GBCI GBDC GBIO GCI
GDDY GDEN GDS GDYN GE GEF GEHC GEN GEO GES GFF GFL GFS GGG GH GHC GHL GIB GIII GIL GILD
GIS GL GLNG GLOB GLP GLT GLW GM GME GMED GMS GNL GNRC GNW GOLF GOOG GOOGL GOSS GOTU GPC
GPI GPK GPMT GPN GPRE GPRO GPS GRBK GRC GRMN GRPN GRPT GS GSAT GSBD GSHD GT GTES GTLB
GTLS GTN GTY GVA GWH GWRE GWRS GXO GYRO H HAE HAIN HAL HALO HAS HAYN HBI HBIO HCA HCC
HCI HCP HCSG HD HE HEAR HEES HEI HELE HEP HES HFWA HGV HHC HI HIFS HIG HIW HL HLF HLIO
HLIT HLNE HLT HLX HMN HMST HOG HOLX HOMB HON HOOD HOPE HPE HPK HPP HPQ HR HRB HRI HRL
HRMY HRT HRTG HRTX HSBC HSIC HSII HSKA HST HSTM HSY HT HTBK HTH HTHT HTLD HTLF HTZ HUBB
HUBG HUBS HUM HUN HURN HUYA HVT HWC HWM HXL HY HYLN HYZN HZO I IAC IART IBCP IBEX IBIO
IBKR IBM IBN IBP IBTX ICD ICE ICFI ICLR ICUI IDA IDCC IDXX IEX IFF IGT IHRT IIIN IIIV
IIPR ILMN IMAX IMGN IMMR IMO IMPL INBK INBX INCR INCY INDB INFA INFN INFO INFY INGN INGR
INMD INN INO INSE INSG INSM INSP INST INT INTA INTC INTU INVA INVH INZY IOR IOSP IOVA
IP IPAR IPG IPGP IQV IR IRBT IRDM IRM IRT IRTC IRWD ISPR ISRG IT ITCI ITGR ITI ITIC ITOS
ITRI ITT ITUB ITW IVR IVT IVZ J JACK JAKK JBGS JBHT JBL JBLU JBSS JBT JCI JEF JKHY JLL
JNJ JNPR JOBS JOE JOUT JPM JRVR JWN JYNT K KALU KAR KBH KBR KDP KE KELYA KEN KEP KEX KEY
KEYS KFRC KFY KHC KIDS KIM KKR KLAC KLIC KMB KMI KMPR KMT KMX KN KNL KNSL KNX KO KODK
KOS KR KRC KRG KRNT KRO KRON KROS KRP KRYS KSS KSU KTB KTOS KURA KVHI KW KWR KYMR L LAC
LAD LAKE LAND LANV LARK LASR LAZ LAZR LB LBRDA LBRDK LBTYA LBTYK LC LCI LCID LDOS LE LEA
LECO LEG LEGN LEN LEVI LFUS LGF.A LGF.B LGIH LH LHCG LHX LILA LILAK LIN LINC LIND LITE
LIVN LKFN LKQ LLY LMAT LMB LMND LMNR LMT LNC LNG LNN LNT LNTH LOB LOCO LOGM LOMA LOPE
LOVE LOW LPLA LPRO LPSN LPX LRCX LRN LSCC LSTR LTCH LTH LU LUMN LUV LVS LW LXP LYB LYV
LZ LZB M MAA MAC MAIN MAN MANH MANU MAR MARA MAS MASI MAT MATV MATW MATX MAXR MBI MC MCB
MCBS MCD MCFT MCHP MCK MCO MCRI MCS MCY MD MDB MDC MDGL MDLZ MDRX MDT MED MEDP MEG MEI
MEOH MET MFA MFC MFG MGEE MGM MGNI MGP MGPI MGRC MGTX MGY MHK MHO MIDD MIK MIME MIR MIRM
MITK MIXT MKC MKL MKSI MKTX ML MLHR MLI MLM MLNX MLR MMC MMI MMM MMS MMSI MNDT MNKD MNP
MNRL MNRO MNSB MNST MO MOD MODG MODN MODV MOG.A MOH MOMO MOS MOV MP MPAA MPC MPLN MPWR
MQ MR MRC MRCY MRK MRNA MRO MRSN MRTN MRVI MRVL MS MSA MSBI MSCI MSEX MSFT MSGE MSGN MSGS
MSI MSM MSTR MTB MTCH MTD MTDR MTEM MTG MTH MTN MTNB MTRN MTRX MTSI MTTR MTW MTX MTZ MU
MUR MUSA MVIS MX MXL MYE MYGN MYRG NAPA NAT NATH NATR NAVI NBHC NBIX NBTB NCLH NCMI NCNO
NCR NCTY NDAQ NDSN NE NEM NEO NEOG NEP NERV NESR NET NEU NEWR NEX NFG NFLX NFTG NG NGD
NGL NGM NGMS NGVT NHI NI NICE NICK NKE NKTR NL NMG NMIH NMR NNBR NNDM NNI NNN NOC NOG
NOK NOMD NORD NOV NOVA NOW NPK NPO NR NRG NRP NRXP NS NSA NSC NSIT NSP NTAP NTB NTCO
NTES NTNX NTR NTRS NTST NU NUAN NUE NUS NUVA NUVI NUVL NVAX NVCR NVDA NVEC NVEE NVEI NVGS
NVO NVR NVRO NVST NVT NVTS NWBI NWE NWFL NWL NWN NWS NWSA NX NXGN NXPI NXRT NXST NYCB NYT
NYTEX O OAS OC OCDX OCFC OCGN OCN OCSL ODD ODFL ODP OFC OFG OFIX OGE OGN OGS OHI OI OII
OIS OKE OKLO OKTA OLED OLLI OLMA OLN OLO OMC OMCL OMER OMEX OMF OMI ON ONEM ONEW ONON
ONTO ONVO OPCH OPEN OPK OPY OR ORA ORAN ORCC ORCL ORGN ORI ORIC ORLY ORN ORRF OSCR OSIS
OSK OSPN OSTK OSUR OTEX OTIS OTLK OTRA OUT OVLY OVV OWL OXM OXY OZK PACB PACK PACW PAG
PAGP PAGS PAHC PAM PANW PARA PARR PATH PATK PAVM PAX PAYC PAYO PAYX PB PBA PBF PBH PBI
PBPB PBR PBT PCAR PCG PCH PCOR PCRX PCT PCTI PCTY PCVX PCYO PD PDCE PDCO PDD PDFS PDM
PDO PDS PDSB PEB PECO PEG PEGA PENN PEO PEP PERI PETS PETQ PFBC PFC PFE PFG PFGC PFMT
PFS PFSI PFSW PG PGC PGNY PGR PGRE PGY PH PHAR PHAT PHG PHM PHR PI PII PINC PING PINS
PIPR PK PKE PKG PKI PL PLAB PLAG PLAY PLBY PLCE PLD PLL PLMR PLNT PLRX PLSE PLTK PLTR
PLUG PLUS PLXS PLYA PLYM PM PMT PMTS PNC PNFP PNM PNR PNRG PNT PNW POOL POR PORT POST POWI
POWL PPBI PPC PPG PPIH PPL PR PRA PRAA PRAX PRCT PRDO PRFT PRG PRGO PRGS PRI PRIM PRK
PRKS PRLB PRM PRMW PRO PROG PROS PRTA PRTS PRU PRVA PSA PSB PSMT PSN PSTG PSTL PSTX PSX
PSXP PTC PTCT PTEN PTON PTVE PUBM PUK PUMP PVH PWFL PWOD PWR PWSC PXD PYCR PYPL PYR PYXS
PZZA QCOM QCRH QDEL QFIN QGEN QLYS QNST QRVO QS QSR QTRX QTWO QUAD QUIK QUOT R RACE RAD
RAIL RAIN RAMP RARE RBA RBB RBBN RBC RBCAA RBLX RC RCEL RCII RCKT RCKY RCL RCM RCUS RDFN
RDN RDNT RDVT RDWR RE REAL REET REG REGN REI REKR REPL REPX RES REVG REX REXR REYN RF RFI
RFL RGA RGEN RGLD RGNX RGP RGR RGS RH RHI RHP RIG RIGL RILY RIO RIVN RJF RKLB RKT RL RLAY
RLGT RLGY RLI RLJ RMBL RMBS RMD RMR RNG RNR ROAD ROCK ROG ROIC ROK ROL ROP ROST RPAY RPD
RPM RPRX RPT RRBI RRC RRGB RRR RRX RS RSG RSI RTLR RTO RTX RUN RUSHA RUTH RVLV RVMD RVNC
RVT RXDX RXO RXRX RXT RY RYAM RYAN RYI RYN S SABR SAFM SAFT SAGE SAIA SAIC SAIL SAM SAN
SANA SANM SAP SASR SATS SB SBAC SBCF SBGI SBH SBLK SBOW SBR SBRA SBS SBSI SBUX SC SCCO
SCHL SCHN SCHW SCI SCL SCNV SCOR SCPH SCR SCSC SCU SCVL SCWX SDA SDGR SDRL SE SEAS SEB
SEDG SEE SEIC SELB SEM SENS SEPH SERV SES SEVN SF SFBS SFIX SFL SFM SFNC SG SGFY SGH SGML
SGMO SGRY SHAK SHC SHEN SHI SHLS SHLX SHO SHOO SHOP SHW SHYF SI SIEB SIEN SIFY SIG SIGI
SIGM SIM SINT SITE SITM SIVB SIX SJI SJM SJT SKIL SKIN SKLZ SKM SKT SKX SKY SKYW SLAB SLB
SLCA SLDB SLG SLGN SLI SLM SLN SLNO SLP SLQT SLRC SM SMAR SMBK SMCI SMFG SMG SMLR SMMT
SMP SMPL SMRT SMTC SN SNA SNAP SNBR SNCE SNCR SNCY SND SNDR SNDX SNES SNEX SNI SNN SNOW
SNP SNPS SNV SNX SO SOFI SOHO SOL SOLO SON SONO SONY SOVO SPB SPCE SPFI SPG SPGI SPH SPHR
SPI SPIR SPLK SPLP SPNS SPNT SPOK SPOT SPPI SPR SPRB SPSC SPT SPTN SPWH SPWR SQ SQM SQSP
SR SRAD SRC SRCE SRCL SRDX SRE SRG SRI SRNE SRPT SRRK SRT SRTS SSB SSD SSNC SSP SSRM SSTI
SSTK ST STAA STAG STAY STBA STC STE STEL STEP STER STFC STIM STKL STL STLD STM STN STNE
STNG STOK STR STRA STRC STRL STRO STRS STT STWD STX STZ SU SUI SUM SUMO SUN SUPN SURG SVB
SVC SVRA SWAV SWBI SWCH SWI SWIM SWK SWKS SWM SWN SWX SXC SXI SXT SY SYBT SYBX SYF SYK SYNA
SYNH SYPR SYRS SYY T TA TAC TACT TAL TAP TARO TASK TAST TBBK TBIO TBK TBPH TCBI TCBK TCMD
TCN TCOM TCRR TCS TCX TD TDC TDG TDOC TDS TDUP TDW TDY TECH TECK TEF TEGO TEL TEN TER
TERN TEVA TEX TFC TFFP TFII TFX TFX TG TGH TGI TGLS TGNA TGT TH THC THG THO THR THRM THRN
THRY THS TIGO TIGR TILE TIMB TIS TISI TITN TIXT TJX TK TKC TKR TLRY TLYS TM TMDX TME TMHC
TMO TMP TMUS TNC TNDM TNET TNL TNP TOL TOO TOST TOWN TPC TPG TPH TPIC TPR TPRE TPTX TPVG
TPX TR TRC TRCO TREE TREX TRGP TRI TRIB TRIN TRIP TRMB TRMD TRMK TRN TRNO TRNS TROW TRP
TRS TRST TRTN TRTX TRU TRUE TRUP TRV TRV TRVG TRVI TRVN TSCO TSE TSEM TSHA TSLA TSN TSP
TSQ TSR TSU TT TTC TTCF TTD TTE TTEC TTEK TTMI TTSH TTWO TU TUP TUSK TV TW TWI TWKS TWLO
TWNK TWO TWST TWTR TX TXG TXN TXRH TXT TYL TYME U UA UAA UAL UAN UBA UBER UBSI UCBI UCTT
UDR UE UEIC UFI UFPI UFPT UG UGI UGP UHAL UHS UHT UI UIS UL ULBI ULCC ULH ULTA UMBF UMC
UMH UNB UNF UNFI UNH UNIT UNM UNP UNTY UNVR UONE UONEK UP UPH UPLD UPS UPST UPWK URBN
URGN URI USA USAC USB USCB USFD USLM USM USNA USPH USRD UTHR UTI UTL UTMD UTZ UUUU UVE
UVSP UWMC V VAC VAL VALE VALU VAPO VAT VBF VBIV VBTX VC VCEL VCTR VCYT VECO VEEV VEL VEON
VERI VERU VET VEU VFC VG VGR VHC VHI VIA VIAV VICI VICR VIPS VIR VIRT VIST VITL VIVE VIVO
VKTX VLO VLRS VLY VMC VMD VMEO VMI VMW VNCE VNDA VNE VNET VNO VNOM VNT VNTR VOD VOXX VOYA
VPG VRDN VREX VRM VRNS VRNT VRRM VRSK VRSN VRT VRTS VRTV VRTX VS VSAT VSCO VSEC VSH VST
VSTS VTEX VTGN VTLE VTNR VTR VTRS VTS VUZI VVI VVNT VVV VXRT VYGR VYNE VYNT VZ W WAB WABC
WAFD WAL WASH WAT WBA WBD WBS WBX WCC WCN WD WDAY WDC WDFC WDI WEAT WEBR WEC WEN WERN WES
WEX WFC WFG WFRD WGO WH WHD WHF WHR WIA WIFI WILC WIMI WINA WING WIRE WIT WIX WK WKHS WLK
WLKP WLL WM WMB WMC WMG WMK WMS WMT WNC WNEB WNS WOOF WOR WOW WPC WPM WPRT WPS WRB WRBY
WRLD WRN WRTC WRK WS WSBC WSC WSFS WSM WSO WST WTBA WTFC WTI WTM WTRG WTS WTTR WTW WU WULF
WVE WW WWD WWE WWW WY WYN WYNN X XEL XENE XERS XFOR XHR XIN XL XLNX XM XMTR XNCR XOM XOMA
XP XPEL XPO XPOF XPRO XRAY XRX XYL Y YELP YETI YEXT YI YMAB YOU YPF YUM YUMC Z ZBH ZBRA
ZD ZEN ZG ZGNX ZI ZIM ZION ZIP ZIV ZLAB ZM ZNGA ZS ZTO ZTS ZUO ZVO ZWS ZYME"""

FTSE350 = """AAL ABDN ABF ADM AFN AHT AML ANTO ASC ASHM ASL AUTO AV AZN BA BAB BAG
BAKK BARC BATS BBY BDEV BEZ BEZ BHP BKG BLND BME BNZL BOY BP BPY BREE BRW BRW BT.A BWY
BYG BZM CCEP CCH CCR CLIG CNA CPG CRDA CRH CRST CSN CTEC DARK DC DCC DEC DGE DGOC DLG
DNLM DOM DPLM DPP DRX DUNE EBGI ECM EDIN EDV EMG ENOG ENQ ENT EOG EOG EQN ESP ESS ESP EXPN
EZJ FCIT FCSS FDM FEV FEVR FGEN FHP FISH FISH FLTR FLK FRAS FRAS FRES FRI FXPO GCP GEMD
GENL GENS GFRD GFS GFY GLE GLE GNC GNK GOR GRG GSK GSS GSS HAS HBR HBR HFEL HFD HGG
HIK HILS HL HLCL HLN HMSO HOC HSBA HSP HSV HTG HTG HTWS HUW HVPE HVT IAG ICG ICAG ICP
IDS IGG IHG III IMB IMI INCH INDV INF INPP INTU INV INV IPO IPO IQE ITH ITRK ITV JD
JDW JMAT JTC JUST KGF KIE KNOS LAM LAND LGEN LIO LIT LLOY LMP LRE LSE LSG LSG LSEG LW MAB
MAB1 MDC MGAM MGAM MKS MKSI MLC MMH MNDI MNG MONY MRO MRO MTO MTU MYI NBPE NESF NG NICL NRR
NWG NWR NXT OCDO OCN OLYX OMU ORSTD OSB PAC PAF PAGE PAY PDG PEY PFC PFD PHD PHD PHP PHNX
PNN POLY PROV PRSM PRSM PRU PSDL PSH PSN PSON PZC RACE RAND RAT RBGP RBP RCP RCTK RDSA RDSB
REL RICA RIO RKT RMG RMI RMV RNK RR RR RS1 RTO RWA RWA RWI S32 SAFE SAGA SBRY SDF SDL SDP
SDR SDRG SDRY SDY SEIT SEPL SERE SFE SFOR SGC SGE SGI SGRO SHB SHEL SHI SHI SKG SLA SLE SMDS
SMIN SMOD SMT SMWH SN SN1 SNCL SNN SNX SOLG SOLI SONA SPI SPT SPX SSE SSRM STAN STCM STHR
SVS SVT SXS TALK TATE TBA TBLD TCAP TCG TED TEP TET TEX TFG TFW THRL TLW TPK TPX TRIG TSCO
TT TUP TW TYMN UCG UKW ULVR UTG UTLX UU VOD VSVS WBA WEIR WG WG. WICH WJG WIN WIZZ WMH WOSG
WPP WPS WTAN WTB XPP XPP XPWR YNGA ZEG"""

DE_ALL = "SAP SIE ALV AIR DTE BAS BMW DHL MBG VOW3 MUV2 ADS BAYN IFX RWE BEI DBK EOAN P911 HNR1 MRK FRE SHL CBK MTX BNR HEI RHM SY1 FME HEN3 ENR VNA ZAL SRT3 1COV LIN CON DB1 QIA PAH3 BOSS GXI LHA LEG DIC FRA PUM S92 TKA VOS EVT ADV AIXA AT1 BVB CEC CTO DEQ DWD ECX EVK EVT1 FIE FIE FNTN G1A GBF GFT GLJ GYC HAB HLAG HOT KGX KU2 KWS LPK LXS MOR MTX NDA OSR PBB PFV PSM RHK RRTL SAZ SANT SAX SDF SFQ SHA SHL SIX2 SNG SOW STM3 STO3 SZG SZU TEG TIM TLX TPE TTI TUI UN01 UTDI VTSC VNT VOS WAC WCH WCMK WDI WUW YSN"
FR_ALL = "MC AI OR SAN TTE BNP CS SU ACA EN DG RI STLAP ML SGO DSY VIV AIR CAP CA ENGI ERF GLE KER LR ORA PUB RMS SAF SGO STM TEP UG URW VIE WLN EDF ATO BN EL ADP AF AKE ALO ALS ALV AKE AKR AMN AMPE AMU APAM AROM ATE ATOS AUB AXW BAY BB BBR BCP BEC BIG BIM BN BNR BOL BON BRM BSD BSM BTC BUI BVI CAD CAF CAP CC CDR CDZ CEL CGG CGM CIE CLA CLR CMG CNP CO COA COFA COH COV CRBP2 CRI CRJ CS DEC DEZ DIM DLT DPAM DPT DSY EDEN EDEN EDF EDR EFI EGT EI EIFF ELEC ELO EN ENGI ENX EQS ERA EUCAR EUR EXE EXN EXO FDE FDJ FDR FFI FGR FR FP FTI GBL GBT GEA GET GFC GK GL GLE GPE GROUP GSI GTT HCO HO IBG ICAD IDL ILIAD INFE ING INP IPN IPS JCQ KERY KOF LACR LBP LI LOCAL LR LSS LTA LVMH MAAT MAF MAN MAU MBWS MDM MEDI MERY MF MLEDS MMB MMT MNG MONC MOR MRK MSK NANO NEOEN NEX NHY NK NRG NXI OBT ODET OFI OMER OPN OR ORA ORP OSE OVH PAJ PARRO PARRO PEUG PRBR PRC PSL PUB PUY QDT RCF RCO REP REW RF RI RIBR RIBR RM RNO ROTH ROUP RUI SAF SAN SBB SCHP SCR SDAM SDRR SE SEL SEV SG SGO SK SMCP SOI SOLB SOLUT SPIE SRP SRP STL STMPA SU SUP TCH TEC TFF TIT TKTT TLA TMV TNE TNIE TNL TNP TOTF TOUP TRI TSE TTE UBI UCITS UFF UG UNIBAL URW URW V09A VCT VIE VIR VIV VIVO VK VLA VLB VLTSA VMC VU VPK VRAP WAVE WLN WOR WORLDLINE XI XIOR XPO YANCOAL"
IT_ALL = "ENI ENEL ISP UCG STLA STM G BAMI TIT LDO UCG ITE FCT BPE A2A SRG CPR AMP BMPS MB NEXI UNI PST HER MONC AZM BAZ BMED BPE BSS CPR DAN DIA DLG DIS DMO ERG FBK FCT FIN G HER IG IVG LDO MB MS MN MONC NEXI PIA PIT RACE REC SPM SRG STM STAR STAR SUN TEN TIP TIT TOD TXT UBI UCG UNI UNIR VIS WIN "

HK_ALL = "0005 0700 0939 0941 0002 0003 0011 0012 0017 0027 0066 0083 0101 0175 0285 0288 0293 0316 0322 0386 0388 0669 0688 0762 0823 0857 0883 0939 0960 0968 0992 1038 1044 1088 1093 1109 1113 1177 1209 1211 1299 1398 1810 1876 1928 1997 2018 2020 2269 2313 2318 2319 2382 2388 2628 2688 3328 3690 3968 3988 6098 6862 9618 9888 9988 9999 1800 1888 2018 2196 2333 2601 2688 3333 3618 3968 3988 6030 6823 6862 6881 9618 9633 9888"
JP_ALL = "7203 6758 9984 8306 6861 9432 8035 6098 4519 7974 6902 4063 8058 4661 4502 7267 6501 6954 6723 4452 8411 9437 4568 4503 6273 7011 8031 6503 2914 3382 4578 6367 6301 9433 5108 8802 8604 7751 4543 6752 9022 8801 9101 8766 4005 4021 4061 4188 4204 4208 4324 4502 4507 4523 4528 4536 4543 4544 4547 4551 4555 4568 4578 4581 4631 4661 4666 4676 4684 4689 4704 4708 4716 4726 4751 4755 4833 4901 4902 4911 4917 4921 4923 4927 4966 4967 4971 4974 4975 4977 5001 5002 5007 5008 5012 5013 5015 5019 5020 5021 5101 5107 5108 5110 5186 5191 5201 5202 5214 5232 5233 5234 5301 5304 5332 5333 5334 5344 5345 5401 5406 5411 5423 5444 5463 5471 5541 5563 5631 5701 5706 5707 5711 5713 5714 5715 5721 5729 5801 5802 5803 5851 5901 5929 5932 5938 5943 5947 5949 5970 5975 5991 6005 6013 6023 6062 6098 6113 6134 6135 6136 6141 6146 6201 6268 6273 6301 6305 6326 6330 6361 6367 6371 6383 6395 6406 6417 6425 6432 6434 6436 6448 6457 6460 6465 6471 6473 6474 6481 6501 6502 6503 6504 6506 6581 6586 6645 6674 6701 6702 6703 6723 6724 6727 6728 6750 6752 6753 6754 6755 6756 6758 6762 6770 6807 6839 6841 6845 6850 6857 6861 6869 6890 6902 6920 6925 6941 6952 6954 6971 6976 6981 6988 7004 7011 7012 7013 7014 7201 7202 7203 7205 7211 7220 7224 7230 7231 7238 7242 7259 7261 7267 7269 7270 7272 7276 7278 7380 7412 7421 7453 7522 7581 7594 7616 7624 7649 7701 7731 7733 7735 7741 7747 7751 7752 7762 7817 7832 7860 7867 7912 7915 7936 7951 7974 7984 7987 8001 8015 8020 8028 8031 8035 8053 8058 8060 8074 8086 8090 8098 8111 8113 8117 8129 8136 8173 8227 8233 8240 8252 8267 8273 8279 8282 8283 8303 8304 8306 8308 8316 8329 8331 8332 8334 8341 8342 8343 8354 8355 8356 8358 8359 8361 8369 8377 8381 8386 8388 8411 8412 8418 8473 8508 8515 8572 8584 8591 8593 8595 8596 8601 8604 8606 8616 8622 8628 8697 8698 8709 8725 8750 8755 8766 8771 8795 8801 8802 8803 8804 8815 8830 8841 8904 8905 8919 8934 8935 8954 8956 8957 8958 8960 8963 8964 8967 8984 8985 8987 9001 9005 9007 9009 9020 9021 9022 9024 9041 9042 9044 9045 9048 9064 9065 9066 9067 9068 9069 9072 9074 9076 9099 9101 9104 9107 9142 9143 9201 9202 9232 9301 9302 9303 9308 9321 9364 9401 9404 9405 9409 9412 9413 9418 9432 9433 9434 9435 9437 9442 9501 9502 9503 9504 9505 9506 9507 9508 9509 9531 9532 9533 9543 9551 9602 9603 9613 9616 9619 9621 9622 9626 9628 9682 9684 9687 9697 9735 9742 9744 9766 9831 9843 9861 9880 9889 9900 9930 9936 9945 9946 9947 9948 9962 9983 9984 9987 9989 9991 9994 9997"
SG_ALL = "D05 O39 U11 Z74 S63 S68 U96 C07 C31 C38U N2IU F34 H78 G13 C52 C09 C61U S58 Y92 U14 J36 J37 V03 M44U D01 BN4 A17U M1Z T82U C6L 5CP 5UX 8AZ 9CI A4Y A7RU ADN AIY AJBU AWC AWX AWZ B2F B61U BLS C2PU C8L C8R C9Q CMOU E28 E50 EB5 EDR G07 G13 G3B H13 H20 H30 HMN J85 K6S K71U LJ3 M03 ME8U N21 NRR O08 O32 P15 P8Z P9D PEX Q0F Q5T RE4 S08 S41 S59 SK3 T14 T39 T55 U06 U09 U10 U77 UD1 UD2 V01 W05 X22 XJB XMH Z25 Z77"
AU_ALL = "BHP CBA CSL NAB WBC ANZ WES MQG WDS RIO TLS GMG WOW COL FMG TCL ALL STO WPL APA RMD NCM MGR SHL IAG SCG SUN QBE ORG BXB AMC TCL REA NST MIN JBH CAR CPU LLC BSL EVN WTC XRO QAN AGL TAH ILU WOR PMGOLD S32 BLD BOQ BEN ASX JHX LOV IGO NWS ORA SHL CWY BBN BKT CYBG CGF COH COL COR CPU CQR CRN CSL CTD CTP CWN CWP CWY CYG DOW EBO EDV EHE ELO EMB ENN EVN FLT FMG FPH GMG GNC GOR GOZ GPT HMY HUM HVN IAG IEL IFL ILU IMU INA ING ING IPL JHG JHX JLG JMS KAR KMD KPG LGI LIC LLC LNK LOV LTR LYC MCR MFG MGR MIN MP1 MPL MQG NAB NAN NCK NDO NEC NEU NEX NGI NHC NIC NSR NST NTD NUF NVX NWH NWL NWS OBE OML ORI ORE ORG ORI OSH PAN PBH PDL PLS PMC PME PMV PNR PNW POW PPE PPH PPT PRN PRU PSQ PTM PWH PXX QAL QAN QBE QIP QUB RBL RDC RDY REH REP RFG RHC RIC RIO RMD RMS RPM RRL RWC S32 SBM SCG SCP SDF SEK SFR SGF SGM SGP SGR SHL SIG SIQ SKT SKO SLR SNZ SOL SPK SRG SSM STO SUL SUN SVW SXY SYA SYD SYR TAH TCL TLG TLS TLX TNE TOU TPG TWE TYR URW VCX VEA VHT VMY VOC WBC WCB WDS WES WGN WGX WHC WOR WOW WPL WSA WTC XRO Z1P ZIP"


async def qualify(ib, exchange, currency, tickers, out):
    from ib_insync import Stock
    # Dedup clean
    tickers = sorted(set(t.strip() for t in tickers.split() if t.strip() and len(t) <= 12))
    log.info("%s/%s: %d candidates", exchange, currency, len(tickers))
    ok = fail = 0
    for i in range(0, len(tickers), 50):
        chunk = tickers[i:i+50]
        try:
            qs = await ib.qualifyContractsAsync(*[Stock(t, exchange, currency) for t in chunk])
        except Exception:
            fail += len(chunk); continue
        for q in qs:
            if q.conId:
                out.append({
                    "symbol": q.symbol, "con_id": q.conId,
                    "exchange": q.exchange or exchange,
                    "currency": q.currency or currency, "sec_type": "STK",
                })
                ok += 1
            else:
                fail += 1
        await asyncio.sleep(0.3)
    log.info("  %s/%s OK=%d fail=%d", exchange, currency, ok, fail)


async def pull_full_nasdaq(ib, contracts):
    """Pull the full NASDAQ listing via reqMatchingSymbols across each
    letter and 2-letter prefix, then qualify."""
    from ib_insync import Stock
    seen_syms = set()
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    all_candidate_syms = set()

    # Scan each letter for matching symbols (returns up to ~16 per query)
    for L1 in letters:
        try:
            matches = await ib.reqMatchingSymbolsAsync(L1)
            for m in matches or []:
                c = m.contract
                if c.secType == "STK" and c.primaryExchange in ("NASDAQ","NASDAQ.NMS","ISLAND","ARCA","NYSE","AMEX","BATS","IEX"):
                    all_candidate_syms.add(c.symbol)
        except Exception as e:
            log.debug("reqMatchingSymbols %s failed: %s", L1, e)
        await asyncio.sleep(0.05)
        # Also dig with two-letter combos for more coverage
        for L2 in letters[:10]:  # cap to 260 queries total
            try:
                matches = await ib.reqMatchingSymbolsAsync(L1 + L2)
                for m in matches or []:
                    c = m.contract
                    if c.secType == "STK" and c.primaryExchange in ("NASDAQ","NASDAQ.NMS","ISLAND","ARCA","NYSE","AMEX","BATS","IEX"):
                        all_candidate_syms.add(c.symbol)
            except Exception:
                pass
            await asyncio.sleep(0.05)

    log.info("NASDAQ/US full scan found %d candidate symbols", len(all_candidate_syms))
    # Qualify in bulk (we already know they're valid from reqMatchingSymbols,
    # but we still need the con_id)
    syms_list = sorted(all_candidate_syms)
    for i in range(0, len(syms_list), 50):
        chunk = syms_list[i:i+50]
        try:
            qs = await ib.qualifyContractsAsync(*[Stock(t, "SMART", "USD") for t in chunk])
            for q in qs:
                if q.conId and (q.symbol, "SMART") not in seen_syms:
                    contracts.append({
                        "symbol": q.symbol, "con_id": q.conId,
                        "exchange": "SMART", "currency": "USD", "sec_type": "STK",
                    })
                    seen_syms.add((q.symbol, "SMART"))
        except Exception:
            continue
        await asyncio.sleep(0.3)
    log.info("NASDAQ/US qualified: %d", len(contracts))


async def pull_full_lse(ib, contracts):
    """Pull FTSE 350 + AIM 100 + additional LSE names via letter scan."""
    from ib_insync import Stock
    all_syms = set()
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    for L1 in letters:
        try:
            matches = await ib.reqMatchingSymbolsAsync(L1)
            for m in matches or []:
                c = m.contract
                if c.secType == "STK" and c.primaryExchange in ("LSE","LSEETF","LSEIOB"):
                    all_syms.add(c.symbol)
        except Exception:
            pass
        await asyncio.sleep(0.05)
        for L2 in letters[:10]:
            try:
                matches = await ib.reqMatchingSymbolsAsync(L1 + L2)
                for m in matches or []:
                    c = m.contract
                    if c.secType == "STK" and c.primaryExchange in ("LSE","LSEETF","LSEIOB"):
                        all_syms.add(c.symbol)
            except Exception:
                pass
            await asyncio.sleep(0.05)
    log.info("LSE full scan found %d candidate symbols", len(all_syms))
    syms_list = sorted(all_syms)
    added = 0
    seen = {(c["symbol"], c["exchange"]) for c in contracts}
    for i in range(0, len(syms_list), 50):
        chunk = syms_list[i:i+50]
        try:
            qs = await ib.qualifyContractsAsync(*[Stock(t, "LSE", "GBP") for t in chunk])
            for q in qs:
                if q.conId and (q.symbol, "LSE") not in seen:
                    contracts.append({
                        "symbol": q.symbol, "con_id": q.conId,
                        "exchange": "LSE", "currency": "GBP", "sec_type": "STK",
                    })
                    seen.add((q.symbol, "LSE"))
                    added += 1
        except Exception:
            continue
        await asyncio.sleep(0.3)
    log.info("LSE additional qualified: %d", added)


async def main():
    from ib_insync import IB
    ib = IB()
    await ib.connectAsync("127.0.0.1", 4002, clientId=172, readonly=True, timeout=30)
    log.info("connected; qualifying wide universe across 10 exchanges + full NASDAQ + LSE")
    contracts = []

    # Static lists first (known constituents)
    await qualify(ib, "SMART",  "USD", SP500, contracts)
    await qualify(ib, "SMART",  "USD", RUSSELL1000_ADDITIONAL, contracts)

    # Then the NEW full-exchange letter-scan pulls (NASDAQ + LSE)
    await pull_full_nasdaq(ib, contracts)
    await pull_full_lse(ib, contracts)

    # Other exchanges remain the curated index lists
    await qualify(ib, "LSE",    "GBP", FTSE350, contracts)
    await qualify(ib, "IBIS",   "EUR", DE_ALL, contracts)
    await qualify(ib, "SBF",    "EUR", FR_ALL, contracts)
    await qualify(ib, "BVME",   "EUR", IT_ALL, contracts)
    await qualify(ib, "SEHK",   "HKD", HK_ALL, contracts)
    await qualify(ib, "TSEJ",   "JPY", JP_ALL, contracts)
    await qualify(ib, "SGX",    "SGD", SG_ALL, contracts)
    await qualify(ib, "ASX",    "AUD", AU_ALL, contracts)

    ib.disconnect()

    # Dedupe by (symbol, exchange)
    seen = set(); uniq = []
    for c in contracts:
        k = (c["symbol"], c["exchange"])
        if k not in seen:
            seen.add(k); uniq.append(c)

    # Mark top 20 US megacaps fast_path
    fast = {"AAPL","MSFT","NVDA","AMZN","GOOGL","META","TSLA","AVGO","AMD","NFLX",
            "LLY","JPM","V","XOM","WMT","UNH","JNJ","HD","ORCL","COST"}
    for c in uniq:
        c["fast"] = (c["symbol"] in fast and c["exchange"] in ("SMART","NASDAQ","NYSE"))

    lines = ["# AEGIS V5 2500-ticker universe (auto-qualified)\n"]
    for c in uniq:
        lines += [
            "[[contracts]]",
            f'symbol = "{c["symbol"]}"',
            f'con_id = {c["con_id"]}',
            f'exchange = "{c["exchange"]}"',
            f'sec_type = "{c["sec_type"]}"',
            f'currency = "{c["currency"]}"',
            f'fast = {"true" if c["fast"] else "false"}',
            "",
        ]
    OUT.write_text("\n".join(lines))
    by_ex = Counter(c["exchange"] for c in uniq)
    log.info("total qualified: %d", len(uniq))
    for ex, n in by_ex.most_common():
        log.info("  %s: %d", ex, n)


if __name__ == "__main__":
    asyncio.run(main())
