global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: aegis_engine_host
    static_configs:
      - targets: ["localhost:9101"]
  - job_name: aegis_metrics_feeder
    static_configs:
      - targets: ["localhost:9103"]
  - job_name: aegis_data_flow
    static_configs:
      - targets: ["localhost:9104"]
