"""
NZT-48 Trading System — SQLite Database
Section 54: 22 tables as defined in the spec + addendum.
Shared between the signal engine and the Command Center FastAPI backend.

Tables (original 8):
  signals       — Every signal generated by any strategy
  trades        — Every executed trade with full journal fields
  positions     — Open positions across all bots
  regime_history — Regime state transitions with context
  ticker_profiles — Per-ticker performance profiles (learning engine)
  restrictions  — Portfolio Overseer restriction table
  daily_summary — Daily rollup per bot
  bot_allocations — Multi-bot capital allocation tracking

Tables (addendum 6):
  virtual_positions  — Paper-trade / virtual position tracking
  virtual_trades     — Completed virtual trades with full analytics
  equity_snapshots   — Daily equity curve snapshots with benchmarks
  indicator_scores   — Per-indicator accuracy and effectiveness scoring
  move_attributions  — Post-hoc attribution of price moves to drivers
  market_data        — OHLCV market data cache

Tables (execution & audit 5):
  strategy_daily_stats       — Per-strategy daily P&L attribution
  partial_executions         — Profit ladder audit trail
  firewall_events            — Emotional firewall audit log
  regime_transition_actions  — Regime flip audit trail
  equity_intraday            — Hourly equity snapshots
"""

from __future__ import annotations

import sqlite3
import logging
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Generator

from core.scoped_query import ScopedQuery

logger = logging.getLogger("nzt48.database")

# Default path relative to project root
DEFAULT_DB_PATH = Path(__file__).parent.parent / "data" / "nzt48.db"


# === Column Whitelist for SQL Injection Prevention ===

VALID_COLUMNS: dict[str, set[str]] = {
    "signals": {
        "id", "timestamp", "ticker", "strategy", "direction", "confidence",
        "entry", "stop", "target_1r", "target_2r", "regime", "status",
        "bot", "bot_instance", "risk_dollars", "risk_pct", "shares",
        "rvol", "gex_regime", "time_window", "patterns", "isa_ticker",
        "isa_leverage", "overseer_status", "portfolio_heat",
        "rejection_reason", "qualification_log", "confidence_breakdown",
        "timeframe_layer", "created_at",
    },
    "trades": {
        "id", "signal_id", "bot", "bot_instance", "ticker", "direction",
        "strategy", "entry_price", "exit_price", "stop_price", "shares",
        "risk_dollars", "risk_percent", "pnl_dollars", "pnl_r_multiple",
        "gross_pnl", "commissions", "net_pnl", "entry_quality",
        "exit_quality", "confidence_score", "regime_state", "sector_rs",
        "macro_score", "gex_regime", "dix_reading", "internals_composite",
        "vix_level", "calendar_risk", "patterns_detected", "reason_codes",
        "emotional_state", "firewall_triggers", "what_worked",
        "what_failed", "improvement_note", "would_take_again",
        "time_entered", "time_exited", "duration_minutes",
    },
    "positions": {
        "id", "trade_id", "signal_id", "bot", "bot_instance", "ticker",
        "direction", "entry", "shares", "current_stop", "original_stop",
        "ladder_rung", "remaining_pct", "current_price", "unrealised_pnl",
        "unrealised_r", "risk_dollars", "entry_time", "last_update",
    },
    "restrictions": {
        "id", "bot_instance", "restriction_type", "value", "reason",
        "created_at", "expires_at",
    },
    "regime_history": {
        "id", "timestamp", "state", "confidence", "qqq_vs_vwap",
        "spy_vs_vwap", "ema_alignment", "vix", "gex", "dix",
        "internals_composite", "trigger_reason",
    },
    "daily_summary": {
        "id", "date", "bot", "trades_taken", "signals_received",
        "signals_skipped", "daily_pnl_dollars", "daily_pnl_percent",
        "win_count", "loss_count", "avg_r_multiple", "largest_winner_r",
        "largest_loser_r", "regime_today", "emotional_grade",
        "one_sentence_lesson", "tomorrow_plan",
    },
    "bot_allocations": {
        "id", "date", "bot_instance", "target_pct", "actual_pct",
        "capital_allocated",
    },
    "virtual_positions": {
        "id", "signal_id", "bot", "bot_instance", "ticker", "direction",
        "strategy", "entry_price", "entry_time", "shares", "risk_dollars",
        "initial_stop", "current_stop", "ladder_rung", "unrealised_pnl",
        "unrealised_r", "peak_r", "trough_r", "commission", "slippage",
        "status", "indicator_snapshot", "regime_at_entry", "confidence",
        "confidence_layers", "remaining_pct", "created_at",
        "time_window", "portfolio_heat", "concurrent_positions",
        "premarket_alignment", "sector_rs", "vix_at_entry",
        "market_direction_spy", "days_since_last_signal",
        "gap_classification", "news_catalyst", "earnings_proximity",
    },
    "virtual_trades": {
        "id", "position_id", "signal_id", "bot", "bot_instance", "ticker",
        "direction", "strategy", "entry_price", "exit_price", "entry_time",
        "exit_time", "shares", "risk_dollars", "gross_pnl", "net_pnl",
        "commission", "slippage", "r_multiple", "entry_quality",
        "exit_quality", "exit_reason", "duration_minutes",
        "regime_at_entry", "regime_at_exit", "confidence",
        "indicator_snapshot_entry", "indicator_snapshot_exit",
        "peak_r", "trough_r", "partials", "failure_category", "created_at",
        "time_window", "portfolio_heat", "concurrent_positions",
        "premarket_alignment", "sector_rs_entry", "vix_at_entry",
        "vix_at_exit", "market_direction_during", "gap_classification",
        "news_catalyst", "earnings_proximity",
        "mae_time_minutes", "mfe_time_minutes", "exit_efficiency",
        "slippage_model_vs_actual", "firewall_cooldown_active",
        "tournament_rank", "missed_gain_by_early_exit", "missed_loss_by_late_exit",
    },
    "equity_snapshots": {
        "date", "starting_equity", "realised_pnl", "unrealised_pnl",
        "ending_equity", "open_positions", "trades_closed", "wins",
        "losses", "commission_total", "slippage_total", "max_drawdown_pct",
        "regime_primary", "system_iq", "annualised_pace",
        "benchmark_spy", "benchmark_qqq", "benchmark_smh",
    },
    "indicator_scores": {
        "id", "indicator_name", "regime", "trades_evaluated",
        "correct_predictions", "accuracy_pct", "avg_r_correct",
        "avg_r_wrong", "effectiveness_score", "confidence_adjustment",
        "period_start", "period_end", "updated_at",
    },
    "move_attributions": {
        "id", "ticker", "date", "move_pct", "direction",
        "primary_driver", "secondary_driver", "explanation",
        "indicators_at_time", "created_at",
    },
    "market_data": {
        "ticker", "timestamp", "open", "high", "low", "close", "volume",
    },
    "premarket_briefs": {
        "id", "timestamp", "scan_window", "market_bias", "bias_confidence",
        "brief_json", "telegram_sent", "created_at",
    },
    "missed_trades": {
        "id", "timestamp", "ticker", "direction", "strategy", "confidence",
        "entry", "stop", "target_1r", "rejection_reason",
        "price_at_rejection", "price_1h_later", "price_4h_later",
        "price_eod", "would_have_hit_target", "would_have_hit_stop",
        "hypothetical_r", "outcome", "created_at",
    },
    "trade_autopsies": {
        "trade_id", "ticker", "strategy", "direction",
        "setup_grade", "setup_notes", "timing_grade", "timing_notes",
        "management_grade", "management_notes",
        "market_context_grade", "market_context_notes",
        "exit_efficiency", "optimal_exit_r", "actual_exit_r",
        "primary_lesson", "indicator_verdict", "overall_grade",
        "created_at",
    },
    "strategy_daily_stats": {
        "id", "date", "strategy", "trades", "wins", "losses",
        "gross_pnl", "net_pnl", "avg_r", "best_r", "worst_r",
        "win_rate", "profit_factor", "avg_duration_minutes",
    },
    "partial_executions": {
        "id", "position_id", "timestamp", "rung", "action",
        "shares_sold", "sell_pct", "price", "pnl_realized",
        "r_at_execution", "new_stop", "created_at",
    },
    "firewall_events": {
        "id", "timestamp", "pattern", "signal_ticker", "signal_direction",
        "signal_strategy", "signal_confidence", "action_taken", "reason",
        "cooldown_until", "created_at",
    },
    "regime_transition_actions": {
        "id", "timestamp", "old_regime", "new_regime", "action_taken",
        "positions_affected", "tickers_closed", "realized_pnl", "created_at",
    },
    "equity_intraday": {
        "id", "timestamp", "equity", "unrealised_pnl", "realised_pnl_today",
        "open_positions", "max_drawdown_intraday_pct", "regime", "created_at",
    },
    "learning_state": {
        "module", "state_json", "updated_at",
    },
}


def _validate_columns(table: str, columns: set[str] | list[str]) -> None:
    """Validate column names against the whitelist. Raises ValueError on invalid columns."""
    valid = VALID_COLUMNS.get(table)
    if valid is None:
        raise ValueError(f"Unknown table: {table}")
    invalid = set(columns) - valid
    if invalid:
        raise ValueError(f"Invalid column names for table '{table}': {invalid}")


def get_connection(db_path: str | Path | None = None) -> sqlite3.Connection:
    """Create a new SQLite connection with WAL mode for concurrent reads."""
    if db_path is None:
        db_path = DEFAULT_DB_PATH
    db_path = Path(db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(str(db_path), timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA busy_timeout=5000")
    conn.row_factory = sqlite3.Row
    return conn


@contextmanager
def transaction(db_path: str | Path | None = None) -> Generator[sqlite3.Connection, None, None]:
    """Context manager for database transactions with auto-commit/rollback."""
    conn = get_connection(db_path)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db(db_path: str | Path | None = None) -> None:
    """Create all 23 tables if they don't exist.
    Called once at startup. Schema matches the spec + addendum exactly."""

    with transaction(db_path) as conn:
        # Table 1: signals — Every signal generated by any strategy
        conn.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id TEXT PRIMARY KEY,
                timestamp TEXT NOT NULL,
                ticker TEXT NOT NULL,
                strategy TEXT NOT NULL,
                direction TEXT NOT NULL,
                confidence REAL NOT NULL,
                entry REAL,
                stop REAL,
                target_1r REAL,
                target_2r REAL,
                regime TEXT,
                status TEXT DEFAULT 'PENDING',
                bot TEXT,
                bot_instance TEXT,
                risk_dollars REAL,
                risk_pct REAL,
                shares INTEGER,
                rvol REAL,
                gex_regime TEXT,
                time_window TEXT,
                patterns TEXT,
                isa_ticker TEXT,
                isa_leverage TEXT,
                overseer_status TEXT DEFAULT 'CLEAR',
                portfolio_heat REAL,
                rejection_reason TEXT,
                qualification_log TEXT,
                confidence_breakdown TEXT,
                timeframe_layer TEXT,
                created_at TEXT DEFAULT (datetime('now'))
            )
        """)

        # Table 2: trades — Every executed trade with full journal fields
        conn.execute("""
            CREATE TABLE IF NOT EXISTS trades (
                id TEXT PRIMARY KEY,
                signal_id TEXT,
                bot TEXT,
                bot_instance TEXT,
                ticker TEXT NOT NULL,
                direction TEXT NOT NULL,
                strategy TEXT,
                entry_price REAL,
                exit_price REAL,
                stop_price REAL,
                shares INTEGER,
                risk_dollars REAL,
                risk_percent REAL,
                pnl_dollars REAL,
                pnl_r_multiple REAL,
                gross_pnl REAL,
                commissions REAL,
                net_pnl REAL,
                entry_quality REAL,
                exit_quality REAL,
                confidence_score REAL,
                regime_state TEXT,
                sector_rs REAL,
                macro_score REAL,
                gex_regime TEXT,
                dix_reading REAL,
                internals_composite INTEGER,
                vix_level REAL,
                calendar_risk TEXT,
                patterns_detected TEXT,
                reason_codes TEXT,
                emotional_state TEXT DEFAULT 'CALM',
                firewall_triggers TEXT,
                what_worked TEXT,
                what_failed TEXT,
                improvement_note TEXT,
                would_take_again INTEGER DEFAULT 1,
                time_entered TEXT,
                time_exited TEXT,
                duration_minutes REAL,
                FOREIGN KEY (signal_id) REFERENCES signals(id)
            )
        """)

        # Table 3: positions — Open positions across all bots
        conn.execute("""
            CREATE TABLE IF NOT EXISTS positions (
                id TEXT PRIMARY KEY,
                trade_id TEXT,
                signal_id TEXT,
                bot TEXT,
                bot_instance TEXT,
                ticker TEXT NOT NULL,
                direction TEXT NOT NULL,
                entry REAL,
                shares INTEGER,
                current_stop REAL,
                original_stop REAL,
                ladder_rung INTEGER DEFAULT 0,
                remaining_pct REAL DEFAULT 1.0,
                current_price REAL,
                unrealised_pnl REAL,
                unrealised_r REAL,
                risk_dollars REAL,
                entry_time TEXT,
                last_update TEXT,
                FOREIGN KEY (trade_id) REFERENCES trades(id),
                FOREIGN KEY (signal_id) REFERENCES signals(id)
            )
        """)

        # Table 4: regime_history — Regime state transitions with context
        conn.execute("""
            CREATE TABLE IF NOT EXISTS regime_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                state TEXT NOT NULL,
                confidence REAL,
                qqq_vs_vwap REAL,
                spy_vs_vwap REAL,
                ema_alignment TEXT,
                vix REAL,
                gex REAL,
                dix REAL,
                internals_composite INTEGER,
                trigger_reason TEXT
            )
        """)

        # Table 5: ticker_profiles — Per-ticker performance profiles
        conn.execute("""
            CREATE TABLE IF NOT EXISTS ticker_profiles (
                ticker TEXT PRIMARY KEY,
                rolling_60d_wr REAL,
                best_strategy TEXT,
                best_direction TEXT,
                false_breakout_rate REAL,
                optimal_rvol REAL,
                optimal_stop_mult REAL,
                priority_score REAL,
                last_updated TEXT
            )
        """)

        # Table 6: restrictions — Portfolio Overseer restriction table
        conn.execute("""
            CREATE TABLE IF NOT EXISTS restrictions (
                id TEXT PRIMARY KEY,
                bot_instance TEXT,
                restriction_type TEXT NOT NULL,
                value TEXT NOT NULL,
                reason TEXT,
                created_at TEXT DEFAULT (datetime('now')),
                expires_at TEXT
            )
        """)

        # Table 7: daily_summary — Daily rollup per bot
        conn.execute("""
            CREATE TABLE IF NOT EXISTS daily_summary (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                date TEXT NOT NULL,
                bot TEXT,
                trades_taken INTEGER DEFAULT 0,
                signals_received INTEGER DEFAULT 0,
                signals_skipped INTEGER DEFAULT 0,
                daily_pnl_dollars REAL DEFAULT 0,
                daily_pnl_percent REAL DEFAULT 0,
                win_count INTEGER DEFAULT 0,
                loss_count INTEGER DEFAULT 0,
                avg_r_multiple REAL DEFAULT 0,
                largest_winner_r REAL DEFAULT 0,
                largest_loser_r REAL DEFAULT 0,
                regime_today TEXT,
                emotional_grade TEXT DEFAULT 'A',
                one_sentence_lesson TEXT,
                tomorrow_plan TEXT,
                UNIQUE(date, bot)
            )
        """)

        # Table 8: bot_allocations — Multi-bot capital allocation tracking
        conn.execute("""
            CREATE TABLE IF NOT EXISTS bot_allocations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                date TEXT NOT NULL,
                bot_instance TEXT NOT NULL,
                target_pct REAL,
                actual_pct REAL,
                capital_allocated REAL,
                UNIQUE(date, bot_instance)
            )
        """)

        # Table 9: virtual_positions — Paper-trade / virtual position tracking
        conn.execute("""
            CREATE TABLE IF NOT EXISTS virtual_positions (
                id TEXT PRIMARY KEY,
                signal_id TEXT,
                bot TEXT,
                bot_instance TEXT,
                ticker TEXT,
                direction TEXT,
                strategy TEXT,
                entry_price REAL,
                entry_time TEXT,
                shares INTEGER,
                risk_dollars REAL,
                initial_stop REAL,
                current_stop REAL,
                ladder_rung INTEGER DEFAULT 0,
                unrealised_pnl REAL DEFAULT 0,
                unrealised_r REAL DEFAULT 0,
                peak_r REAL DEFAULT 0,
                trough_r REAL DEFAULT 0,
                commission REAL DEFAULT 0,
                slippage REAL DEFAULT 0,
                status TEXT DEFAULT 'OPEN',
                indicator_snapshot TEXT,
                regime_at_entry TEXT,
                confidence INTEGER,
                confidence_layers TEXT,
                remaining_pct REAL DEFAULT 1.0,
                time_window TEXT DEFAULT '',
                portfolio_heat REAL DEFAULT 0,
                concurrent_positions INTEGER DEFAULT 0,
                premarket_alignment TEXT DEFAULT '',
                sector_rs REAL DEFAULT 0,
                vix_at_entry REAL DEFAULT 0,
                market_direction_spy REAL DEFAULT 0,
                days_since_last_signal INTEGER DEFAULT 0,
                gap_classification TEXT DEFAULT '',
                news_catalyst TEXT DEFAULT '',
                earnings_proximity INTEGER DEFAULT -1,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 10: virtual_trades — Completed virtual trades with full analytics
        conn.execute("""
            CREATE TABLE IF NOT EXISTS virtual_trades (
                id TEXT PRIMARY KEY,
                position_id TEXT,
                signal_id TEXT,
                bot TEXT,
                bot_instance TEXT,
                ticker TEXT,
                direction TEXT,
                strategy TEXT,
                entry_price REAL,
                exit_price REAL,
                entry_time TEXT,
                exit_time TEXT,
                shares INTEGER,
                risk_dollars REAL,
                gross_pnl REAL,
                net_pnl REAL,
                commission REAL,
                slippage REAL,
                r_multiple REAL,
                entry_quality REAL,
                exit_quality REAL,
                exit_reason TEXT,
                duration_minutes INTEGER,
                regime_at_entry TEXT,
                regime_at_exit TEXT,
                confidence INTEGER,
                indicator_snapshot_entry TEXT,
                indicator_snapshot_exit TEXT,
                peak_r REAL,
                trough_r REAL,
                partials TEXT,
                failure_category TEXT,
                time_window TEXT DEFAULT '',
                portfolio_heat REAL DEFAULT 0,
                concurrent_positions INTEGER DEFAULT 0,
                premarket_alignment TEXT DEFAULT '',
                sector_rs_entry REAL DEFAULT 0,
                vix_at_entry REAL DEFAULT 0,
                vix_at_exit REAL DEFAULT 0,
                market_direction_during REAL DEFAULT 0,
                gap_classification TEXT DEFAULT '',
                news_catalyst TEXT DEFAULT '',
                earnings_proximity INTEGER DEFAULT -1,
                mae_time_minutes INTEGER DEFAULT 0,
                mfe_time_minutes INTEGER DEFAULT 0,
                exit_efficiency REAL DEFAULT 0,
                slippage_model_vs_actual REAL DEFAULT 0,
                firewall_cooldown_active INTEGER DEFAULT 0,
                tournament_rank INTEGER DEFAULT 0,
                missed_gain_by_early_exit REAL DEFAULT 0,
                missed_loss_by_late_exit REAL DEFAULT 0,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 11: equity_snapshots — Daily equity curve snapshots with benchmarks
        conn.execute("""
            CREATE TABLE IF NOT EXISTS equity_snapshots (
                date TEXT PRIMARY KEY,
                starting_equity REAL,
                realised_pnl REAL,
                unrealised_pnl REAL,
                ending_equity REAL,
                open_positions INTEGER,
                trades_closed INTEGER,
                wins INTEGER,
                losses INTEGER,
                commission_total REAL,
                slippage_total REAL,
                max_drawdown_pct REAL,
                regime_primary TEXT,
                system_iq REAL,
                annualised_pace REAL,
                benchmark_spy REAL,
                benchmark_qqq REAL,
                benchmark_smh REAL
            )
        """)

        # Table 12: indicator_scores — Per-indicator accuracy and effectiveness
        conn.execute("""
            CREATE TABLE IF NOT EXISTS indicator_scores (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                indicator_name TEXT,
                regime TEXT,
                trades_evaluated INTEGER,
                correct_predictions INTEGER,
                accuracy_pct REAL,
                avg_r_correct REAL,
                avg_r_wrong REAL,
                effectiveness_score REAL,
                confidence_adjustment INTEGER DEFAULT 0,
                period_start TEXT,
                period_end TEXT,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 13: move_attributions — Post-hoc attribution of price moves
        conn.execute("""
            CREATE TABLE IF NOT EXISTS move_attributions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                ticker TEXT,
                date TEXT,
                move_pct REAL,
                direction TEXT,
                primary_driver TEXT,
                secondary_driver TEXT,
                explanation TEXT,
                indicators_at_time TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 14: market_data — OHLCV market data cache
        conn.execute("""
            CREATE TABLE IF NOT EXISTS market_data (
                ticker TEXT,
                timestamp TEXT,
                open REAL,
                high REAL,
                low REAL,
                close REAL,
                volume INTEGER,
                PRIMARY KEY (ticker, timestamp)
            )
        """)

        # Table 15: premarket_briefs — Pre-market intelligence snapshots
        conn.execute("""
            CREATE TABLE IF NOT EXISTS premarket_briefs (
                id TEXT PRIMARY KEY,
                timestamp TEXT NOT NULL,
                scan_window TEXT NOT NULL,
                market_bias TEXT,
                bias_confidence REAL,
                brief_json TEXT NOT NULL,
                telegram_sent INTEGER DEFAULT 0,
                created_at TEXT DEFAULT (datetime('now'))
            )
        """)

        # Table 16: missed_trades — Trades that passed qualification but were blocked
        conn.execute("""
            CREATE TABLE IF NOT EXISTS missed_trades (
                id TEXT PRIMARY KEY,
                timestamp TEXT NOT NULL,
                ticker TEXT NOT NULL,
                direction TEXT NOT NULL,
                strategy TEXT,
                confidence REAL,
                entry REAL,
                stop REAL,
                target_1r REAL,
                rejection_reason TEXT,
                price_at_rejection REAL,
                price_1h_later REAL,
                price_4h_later REAL,
                price_eod REAL,
                would_have_hit_target INTEGER DEFAULT 0,
                would_have_hit_stop INTEGER DEFAULT 0,
                hypothetical_r REAL DEFAULT 0,
                outcome TEXT DEFAULT 'UNKNOWN',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 17: trade_autopsies — Automatic post-trade analysis
        conn.execute("""
            CREATE TABLE IF NOT EXISTS trade_autopsies (
                trade_id TEXT PRIMARY KEY,
                ticker TEXT NOT NULL,
                strategy TEXT,
                direction TEXT,
                setup_grade REAL,
                setup_notes TEXT,
                timing_grade REAL,
                timing_notes TEXT,
                management_grade REAL,
                management_notes TEXT,
                market_context_grade REAL,
                market_context_notes TEXT,
                exit_efficiency REAL,
                optimal_exit_r REAL,
                actual_exit_r REAL,
                primary_lesson TEXT,
                indicator_verdict TEXT,
                overall_grade REAL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 18: strategy_daily_stats — Per-strategy daily P&L attribution
        conn.execute("""
            CREATE TABLE IF NOT EXISTS strategy_daily_stats (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                date TEXT NOT NULL,
                strategy TEXT NOT NULL,
                trades INTEGER DEFAULT 0,
                wins INTEGER DEFAULT 0,
                losses INTEGER DEFAULT 0,
                gross_pnl REAL DEFAULT 0,
                net_pnl REAL DEFAULT 0,
                avg_r REAL DEFAULT 0,
                best_r REAL DEFAULT 0,
                worst_r REAL DEFAULT 0,
                win_rate REAL DEFAULT 0,
                profit_factor REAL DEFAULT 0,
                avg_duration_minutes REAL DEFAULT 0,
                UNIQUE(date, strategy)
            )
        """)

        # Table 19: partial_executions — Profit ladder audit trail
        conn.execute("""
            CREATE TABLE IF NOT EXISTS partial_executions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                position_id TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                rung INTEGER NOT NULL,
                action TEXT NOT NULL,
                shares_sold INTEGER DEFAULT 0,
                sell_pct REAL DEFAULT 0,
                price REAL DEFAULT 0,
                pnl_realized REAL DEFAULT 0,
                r_at_execution REAL DEFAULT 0,
                new_stop REAL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 20: firewall_events — Emotional firewall audit log
        conn.execute("""
            CREATE TABLE IF NOT EXISTS firewall_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                pattern TEXT NOT NULL,
                signal_ticker TEXT,
                signal_direction TEXT,
                signal_strategy TEXT,
                signal_confidence REAL,
                action_taken TEXT NOT NULL,
                reason TEXT,
                cooldown_until TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 21: regime_transition_actions — Regime flip audit trail
        conn.execute("""
            CREATE TABLE IF NOT EXISTS regime_transition_actions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                old_regime TEXT NOT NULL,
                new_regime TEXT NOT NULL,
                action_taken TEXT NOT NULL,
                positions_affected INTEGER DEFAULT 0,
                tickers_closed TEXT,
                realized_pnl REAL DEFAULT 0,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 22: equity_intraday — Hourly equity snapshots
        conn.execute("""
            CREATE TABLE IF NOT EXISTS equity_intraday (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                equity REAL NOT NULL,
                unrealised_pnl REAL DEFAULT 0,
                realised_pnl_today REAL DEFAULT 0,
                open_positions INTEGER DEFAULT 0,
                max_drawdown_intraday_pct REAL DEFAULT 0,
                regime TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Table 23: learning_state — Persisted state for learning modules
        conn.execute("""
            CREATE TABLE IF NOT EXISTS learning_state (
                module TEXT PRIMARY KEY,
                state_json TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # === Schema migrations for existing databases ===
        # Add missed_gain/missed_loss columns if they don't exist (v9.1 migration)
        try:
            conn.execute("SELECT missed_gain_by_early_exit FROM virtual_trades LIMIT 1")
        except sqlite3.OperationalError:
            logger.info("Migrating virtual_trades: adding missed_gain_by_early_exit column")
            conn.execute("ALTER TABLE virtual_trades ADD COLUMN missed_gain_by_early_exit REAL DEFAULT 0")
        try:
            conn.execute("SELECT missed_loss_by_late_exit FROM virtual_trades LIMIT 1")
        except sqlite3.OperationalError:
            logger.info("Migrating virtual_trades: adding missed_loss_by_late_exit column")
            conn.execute("ALTER TABLE virtual_trades ADD COLUMN missed_loss_by_late_exit REAL DEFAULT 0")

        # Create indexes for common queries
        conn.execute("CREATE INDEX IF NOT EXISTS idx_signals_ticker ON signals(ticker)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_trades_ticker ON trades(ticker)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades(strategy)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_trades_time ON trades(time_entered)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_positions_bot ON positions(bot_instance)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_positions_ticker ON positions(ticker)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_restrictions_bot ON restrictions(bot_instance)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_regime_time ON regime_history(timestamp)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_daily_date ON daily_summary(date)")

        # Indexes for addendum tables
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vpos_status ON virtual_positions(status)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vpos_ticker_status ON virtual_positions(ticker, status)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vpos_bot_instance ON virtual_positions(bot_instance)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vtrades_ticker ON virtual_trades(ticker)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vtrades_strategy ON virtual_trades(strategy)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vtrades_exit_time ON virtual_trades(exit_time)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vtrades_entry_time ON virtual_trades(entry_time)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vtrades_bot_instance ON virtual_trades(bot_instance)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_vtrades_failure_cat ON virtual_trades(failure_category)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_iscores_name_regime ON indicator_scores(indicator_name, regime)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_mattrib_ticker_date ON move_attributions(ticker, date)")

        # Indexes for missed_trades
        conn.execute("CREATE INDEX IF NOT EXISTS idx_missed_ticker ON missed_trades(ticker)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_missed_outcome ON missed_trades(outcome)")

        # Indexes for trade_autopsies
        conn.execute("CREATE INDEX IF NOT EXISTS idx_autopsy_strategy ON trade_autopsies(strategy)")

        # Indexes for execution & audit tables
        conn.execute("CREATE INDEX IF NOT EXISTS idx_strat_daily_date ON strategy_daily_stats(date)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_strat_daily_strategy ON strategy_daily_stats(strategy)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_partial_position ON partial_executions(position_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_firewall_pattern ON firewall_events(pattern)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_firewall_ts ON firewall_events(timestamp)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_regime_actions_ts ON regime_transition_actions(timestamp)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_equity_intraday_ts ON equity_intraday(timestamp)")

    logger.info("Database initialized with 23 tables at %s", db_path or DEFAULT_DB_PATH)


# === CRUD Operations ===

def insert_signal(conn: sqlite3.Connection, signal_data: dict[str, Any]) -> None:
    """Insert a new signal record."""
    _validate_columns("signals", signal_data.keys())
    cols = ", ".join(signal_data.keys())
    placeholders = ", ".join(["?"] * len(signal_data))
    conn.execute(
        f"INSERT OR REPLACE INTO signals ({cols}) VALUES ({placeholders})",
        list(signal_data.values())
    )


def insert_trade(conn: sqlite3.Connection, trade_data: dict[str, Any]) -> None:
    """Insert a completed trade record."""
    _validate_columns("trades", trade_data.keys())
    cols = ", ".join(trade_data.keys())
    placeholders = ", ".join(["?"] * len(trade_data))
    conn.execute(
        f"INSERT OR REPLACE INTO trades ({cols}) VALUES ({placeholders})",
        list(trade_data.values())
    )


def upsert_position(conn: sqlite3.Connection, position_data: dict[str, Any]) -> None:
    """Insert or update a position record."""
    _validate_columns("positions", position_data.keys())
    cols = ", ".join(position_data.keys())
    placeholders = ", ".join(["?"] * len(position_data))
    update_clause = ", ".join(
        f"{k} = excluded.{k}" for k in position_data.keys() if k != "id"
    )
    conn.execute(
        f"""INSERT INTO positions ({cols}) VALUES ({placeholders})
            ON CONFLICT(id) DO UPDATE SET {update_clause}""",
        list(position_data.values())
    )


def delete_position(conn: sqlite3.Connection, position_id: str) -> None:
    """Remove a closed position."""
    conn.execute("DELETE FROM positions WHERE id = ?", (position_id,))


def get_open_positions(conn: sqlite3.Connection,
                       bot_instance: str | None = None) -> list[sqlite3.Row]:
    """Get all open positions, optionally filtered by bot instance."""
    if bot_instance:
        return conn.execute(
            "SELECT * FROM positions WHERE bot_instance = ?",
            (bot_instance,)
        ).fetchall()
    return conn.execute("SELECT * FROM positions").fetchall()


def get_active_restrictions(conn: sqlite3.Connection,
                           bot_instance: str | None = None) -> list[sqlite3.Row]:
    """Get active (non-expired) restrictions."""
    query = """
        SELECT * FROM restrictions
        WHERE (expires_at IS NULL OR expires_at > datetime('now'))
    """
    if bot_instance:
        query += " AND bot_instance = ?"
        return conn.execute(query, (bot_instance,)).fetchall()
    return conn.execute(query).fetchall()


def insert_restriction(conn: sqlite3.Connection, restriction_data: dict[str, Any]) -> None:
    """Insert an Overseer restriction."""
    _validate_columns("restrictions", restriction_data.keys())
    cols = ", ".join(restriction_data.keys())
    placeholders = ", ".join(["?"] * len(restriction_data))
    conn.execute(
        f"INSERT OR REPLACE INTO restrictions ({cols}) VALUES ({placeholders})",
        list(restriction_data.values())
    )


def get_recent_signals(conn: sqlite3.Connection,
                       hours: int = 4,
                       ticker: str | None = None) -> list[sqlite3.Row]:
    """Get signals from the last N hours for dedup checking (Stage 1)."""
    query = """
        SELECT * FROM signals
        WHERE timestamp > datetime('now', ?)
    """
    params: list[Any] = [f"-{hours} hours"]
    if ticker:
        query += " AND ticker = ?"
        params.append(ticker)
    query += " ORDER BY timestamp DESC"
    return conn.execute(query, params).fetchall()


def get_daily_trade_count(conn: sqlite3.Connection,
                          bot_instance: str,
                          date: str | None = None) -> int:
    """Count trades taken today by a bot instance (paper + live)."""
    if date is None:
        # UNION: count from both trades (live) and virtual_trades (paper)
        return conn.execute(
            """SELECT COUNT(*) FROM (
                SELECT id FROM trades WHERE bot_instance = ? AND date(time_entered) = date('now')
                UNION ALL
                SELECT id FROM virtual_trades WHERE bot_instance = ? AND date(exit_time) = date('now')
            )""",
            (bot_instance, bot_instance)
        ).fetchone()[0]
    return conn.execute(
        """SELECT COUNT(*) FROM (
            SELECT id FROM trades WHERE bot_instance = ? AND date(time_entered) = ?
            UNION ALL
            SELECT id FROM virtual_trades WHERE bot_instance = ? AND date(exit_time) = ?
        )""",
        (bot_instance, date, bot_instance, date)
    ).fetchone()[0]


def get_weekly_trade_count(conn: sqlite3.Connection, bot_instance: str) -> int:
    """Count trades this week by a bot instance (paper + live)."""
    return conn.execute(
        """SELECT COUNT(*) FROM (
            SELECT id FROM trades WHERE bot_instance = ? AND time_entered > datetime('now', '-7 days')
            UNION ALL
            SELECT id FROM virtual_trades WHERE bot_instance = ? AND exit_time > datetime('now', '-7 days')
        )""",
        (bot_instance, bot_instance)
    ).fetchone()[0]


def get_daily_pnl(conn: sqlite3.Connection,
                   bot_instance: str | None = None,
                   date: str | None = None) -> float:
    """Get combined P&L for today across specified bot or all bots (paper + live)."""
    if date is None:
        date_clause_trades = "date(time_entered) = date('now')"
        date_clause_vtrades = "date(exit_time) = date('now')"
        params: list[Any] = []
    else:
        date_clause_trades = "date(time_entered) = ?"
        date_clause_vtrades = "date(exit_time) = ?"
        params = [date, date]  # one for each subquery

    if bot_instance:
        query = f"""SELECT COALESCE(SUM(pnl), 0) FROM (
            SELECT pnl_dollars as pnl FROM trades WHERE bot_instance = ? AND {date_clause_trades}
            UNION ALL
            SELECT net_pnl as pnl FROM virtual_trades WHERE bot_instance = ? AND {date_clause_vtrades}
        )"""
        params = [bot_instance] + ([] if date is None else [date]) + [bot_instance] + ([] if date is None else [date])
    else:
        query = f"""SELECT COALESCE(SUM(pnl), 0) FROM (
            SELECT pnl_dollars as pnl FROM trades WHERE {date_clause_trades}
            UNION ALL
            SELECT net_pnl as pnl FROM virtual_trades WHERE {date_clause_vtrades}
        )"""

    return conn.execute(query, params).fetchone()[0]


def get_weekly_pnl(conn: sqlite3.Connection, bot_instance: str | None = None) -> float:
    """Get combined P&L for the rolling 7 days (paper + live)."""
    if bot_instance:
        return conn.execute(
            """SELECT COALESCE(SUM(pnl), 0) FROM (
                SELECT pnl_dollars as pnl FROM trades
                WHERE bot_instance = ? AND time_entered > datetime('now', '-7 days')
                UNION ALL
                SELECT net_pnl as pnl FROM virtual_trades
                WHERE bot_instance = ? AND exit_time > datetime('now', '-7 days')
            )""",
            (bot_instance, bot_instance)
        ).fetchone()[0]
    return conn.execute(
        """SELECT COALESCE(SUM(pnl), 0) FROM (
            SELECT pnl_dollars as pnl FROM trades WHERE time_entered > datetime('now', '-7 days')
            UNION ALL
            SELECT net_pnl as pnl FROM virtual_trades WHERE exit_time > datetime('now', '-7 days')
        )"""
    ).fetchone()[0]


def get_consecutive_losses(conn: sqlite3.Connection, bot_instance: str) -> int:
    """Count consecutive losses for emotional firewall (paper + live).

    B-06 (SK-02): Uses ScopedQuery to scope to current trading session
    (06:00 UK today). Old code used datetime('now', '-12 hours') which
    suffered from BST drift and could still match stale losses from the
    previous session, causing permanent deadlock ('zombie halt').
    """
    sq = ScopedQuery(conn)
    # Prefer virtual_trades (paper mode), fall back to trades (live mode)
    rows = sq.execute(
        """SELECT net_pnl as pnl FROM virtual_trades
           WHERE bot_instance = ?
           ORDER BY exit_time DESC LIMIT 10""",
        (bot_instance,),
        time_column="exit_time",
    ).fetchall()
    if not rows:
        rows = sq.execute(
            """SELECT pnl_dollars as pnl FROM trades
               WHERE bot_instance = ?
               ORDER BY time_exited DESC LIMIT 10""",
            (bot_instance,),
            time_column="time_exited",
        ).fetchall()
    count = 0
    for row in rows:
        if (row["pnl"] or 0) < 0:
            count += 1
        else:
            break
    return count


def insert_regime_history(conn: sqlite3.Connection, data: dict[str, Any]) -> None:
    """Log a regime state transition."""
    _validate_columns("regime_history", data.keys())
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(
        f"INSERT INTO regime_history ({cols}) VALUES ({placeholders})",
        list(data.values())
    )


def upsert_daily_summary(conn: sqlite3.Connection, data: dict[str, Any]) -> None:
    """Insert or update daily summary."""
    _validate_columns("daily_summary", data.keys())
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    update_clause = ", ".join(
        f"{k} = excluded.{k}" for k in data.keys() if k not in ("date", "bot")
    )
    conn.execute(
        f"""INSERT INTO daily_summary ({cols}) VALUES ({placeholders})
            ON CONFLICT(date, bot) DO UPDATE SET {update_clause}""",
        list(data.values())
    )


def insert_premarket_brief(conn: sqlite3.Connection, data: dict[str, Any]) -> None:
    """Insert a pre-market intelligence brief."""
    import json
    brief_json = json.dumps(data) if not isinstance(data.get("brief_json"), str) else data.get("brief_json", "{}")
    conn.execute(
        """INSERT INTO premarket_briefs (id, timestamp, scan_window, market_bias, bias_confidence, brief_json)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (
            data.get("id", f"PMB-{data.get('scan_window', 'UNK')}-{data.get('timestamp', '')}"),
            data.get("timestamp", ""),
            data.get("scan_window", ""),
            data.get("market_bias", "NEUTRAL"),
            data.get("bias_confidence", 0.0),
            brief_json,
        ),
    )


def get_latest_premarket_brief(
    conn: sqlite3.Connection, scan_window: str | None = None,
) -> dict[str, Any] | None:
    """Get the most recent pre-market brief, optionally filtered by scan window."""
    if scan_window:
        row = conn.execute(
            "SELECT * FROM premarket_briefs WHERE scan_window = ? ORDER BY timestamp DESC LIMIT 1",
            (scan_window,),
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT * FROM premarket_briefs ORDER BY timestamp DESC LIMIT 1",
        ).fetchone()
    return dict(row) if row else None


def insert_strategy_daily_stats(conn, data: dict) -> None:
    """Insert or update per-strategy daily stats."""
    _validate_columns("strategy_daily_stats", data.keys())
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    update_clause = ", ".join(
        f"{k} = excluded.{k}" for k in data.keys() if k not in ("date", "strategy")
    )
    conn.execute(
        f"""INSERT INTO strategy_daily_stats ({cols}) VALUES ({placeholders})
            ON CONFLICT(date, strategy) DO UPDATE SET {update_clause}""",
        list(data.values())
    )


def insert_partial_execution(conn, data: dict) -> None:
    """Log a profit ladder partial execution."""
    _validate_columns("partial_executions", data.keys())
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(
        f"INSERT INTO partial_executions ({cols}) VALUES ({placeholders})",
        list(data.values())
    )


def insert_firewall_event(conn, data: dict) -> None:
    """Log an emotional firewall event."""
    _validate_columns("firewall_events", data.keys())
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(
        f"INSERT INTO firewall_events ({cols}) VALUES ({placeholders})",
        list(data.values())
    )


def insert_regime_transition_action(conn, data: dict) -> None:
    """Log a regime transition and its effects."""
    _validate_columns("regime_transition_actions", data.keys())
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(
        f"INSERT INTO regime_transition_actions ({cols}) VALUES ({placeholders})",
        list(data.values())
    )


def insert_equity_intraday(conn, data: dict) -> None:
    """Insert an intraday equity snapshot."""
    _validate_columns("equity_intraday", data.keys())
    cols = ", ".join(data.keys())
    placeholders = ", ".join(["?"] * len(data))
    conn.execute(
        f"INSERT INTO equity_intraday ({cols}) VALUES ({placeholders})",
        list(data.values())
    )


def get_strategy_daily_stats(conn, date: str = None) -> list:
    """Get per-strategy stats for a date (default today)."""
    if date is None:
        return conn.execute(
            "SELECT * FROM strategy_daily_stats WHERE date = date('now') ORDER BY net_pnl DESC"
        ).fetchall()
    return conn.execute(
        "SELECT * FROM strategy_daily_stats WHERE date = ? ORDER BY net_pnl DESC",
        (date,)
    ).fetchall()


def get_firewall_events_today(conn) -> list:
    """Get all firewall events for today."""
    return conn.execute(
        "SELECT * FROM firewall_events WHERE date(timestamp) = date('now') ORDER BY timestamp DESC"
    ).fetchall()


def get_regime_transitions_today(conn) -> list:
    """Get regime transition actions for today."""
    return conn.execute(
        "SELECT * FROM regime_transition_actions WHERE date(timestamp) = date('now') ORDER BY timestamp DESC"
    ).fetchall()


def save_learning_state(conn: sqlite3.Connection, module: str, state_json: str) -> None:
    """Persist learning module state as a JSON blob.
    Used by CorrelationTracker, EdgeDecayEngine, PerformanceAttribution, etc."""
    conn.execute(
        "INSERT OR REPLACE INTO learning_state (module, state_json, updated_at) "
        "VALUES (?, ?, datetime('now'))",
        (module, state_json),
    )


def load_learning_state(conn: sqlite3.Connection, module: str) -> str | None:
    """Load a learning module's persisted state. Returns JSON string or None."""
    row = conn.execute(
        "SELECT state_json FROM learning_state WHERE module = ?",
        (module,),
    ).fetchone()
    return row["state_json"] if row else None
